In [1]:
import pandas as pd
import sqlite3
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score, recall_score
from joblib import dump, load
import openmeteo_requests
import tqdm
from statsmodels.tsa.arima.model import ARIMA
import warnings
import numpy as np

In [3]:
try:
    con = sqlite3.connect(r"C:\Users\demoexam\Desktop\Гурбанов\MachineLearning\Проект №6 (последний срез)\clear_data.db")
    data = pd.read_sql("SELECT * FROM Clear_data", con=con)
except Exception as e:
    print(f"Ошибка в загрузке из базы данных: {e}")

In [4]:
data = data.drop(["level_0", "index"], axis=1)

In [5]:
data = data.drop(["country", "cluster_2", "track_id", "point_id"], axis=1)

In [6]:
data

,time,latitude,longitude,elevation,steps,temperature,water_feature,forest_feature,buildings_feature,place_type,cluster,fire,flood,evacuation,dangerous
0,2012-09-12 21:13:13+00:00,51.505713,104.139225,501.46,3.0,-25.937000,1,3,94,2,2,1,0,0,2
1,2012-09-12 21:13:19+00:00,51.505694,104.139221,505.79,0.0,-25.937000,1,3,94,2,2,1,0,0,2
2,2012-09-12 21:13:20+00:00,51.505693,104.139224,505.79,5.0,-25.937000,1,3,94,2,2,1,0,0,2
3,2012-09-12 21:13:30+00:00,51.505724,104.139204,511.56,1.0,-25.937000,1,3,94,2,2,1,0,0,2
4,2012-09-12 21:13:37+00:00,51.505717,104.139202,514.92,1.0,-25.937000,1,3,94,2,2,1,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2741,2022-07-16 09:35:57+00:00,51.737582,103.428106,669.33,44.0,-29.246500,0,0,0,0,1,0,0,1,1
2742,2022-07-16 09:36:02+00:00,51.737811,103.427860,668.52,44.0,-29.246500,0,0,0,0,1,0,0,1,1
2743,2022-07-16 09:36:07+00:00,51.738017,103.427555,668.27,16.0,-29.246500,0,0,0,0,1,0,0,1,1
2744,2022-07-16 09:36:24+00:00,51.738100,103.427456,668.27,31.0,-29.207499,0,0,0,0,1,0,0,1,1
2745,2022-07-16 09:36:30+00:00,51.738253,103.427259,668.03,0.0,-29.207499,0,0,0,0,1,0,0,1,1

In [7]:
data["time"] = pd.to_datetime(data["time"])

In [8]:
data['date_day'] = data['time'].dt.day
data['date_month'] = data['time'].dt.month
data['date_year'] = data['time'].dt.year
data['date_hour'] = data['time'].dt.hour

In [9]:
data = data.drop("time", axis=1)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(data.drop("fire", axis=1), data["fire"], test_size=0.33, random_state=42)

In [20]:
LR = LogisticRegression(max_iter=5000)

In [21]:
LR.fit(X_train, y_train)

LogisticRegression(max_iter=5000)

In [22]:
GBC = GradientBoostingClassifier()

In [23]:
GBC.fit(X_train, y_train)

GradientBoostingClassifier()

In [24]:
MLPC = MLPClassifier()

In [25]:
MLPC.fit(X_train, y_train)

MLPClassifier()

In [26]:
models = {"MLPClassifier": MLPC, "GradientBoostingClassifier": GBC, "LogisticRegression": LR}

In [27]:
for name_model in models:
    model = models[name_model]
    model_pred = model.predict(X_test)
    model_proba = model.predict_proba(X_test)
    print(f"Модель {name_model}:\n\nТочность: {accuracy_score(y_test, model_pred)}\nПолнота: {recall_score(y_test, model_pred, average="micro")}\nF1-метрика: {f1_score(y_test, model_pred, average="micro")}\nROC-AUC метрика: {roc_auc_score(y_test, model_proba, average="micro", multi_class="ovr")}\n\n")

ValueError: y should be a 1d array, got an array of shape (907, 2) instead.

### Лучше всего будет выбрать алгоритм Логистической Регресии, так как она использует линейные зависимости, которые присуствуют в датасете. Помимо этого это достаточно простой алгоритм и он полностью справляется со своей задачей, брать более сложные алгоритмы смысла не имеет.

In [19]:
dump(models["LogisticRegression"], 'best_model.joblib')

['best_model.joblib']

In [20]:
data

,latitude,longitude,elevation,steps,temperature,water_feature,forest_feature,buildings_feature,place_type,cluster,fire,flood,evacuation,dangerous,date_day,date_month,date_year,date_hour
0,51.505713,104.139225,501.46,3.0,-25.937000,1,3,94,2,2,1,0,0,2,12,9,2012,21
1,51.505694,104.139221,505.79,0.0,-25.937000,1,3,94,2,2,1,0,0,2,12,9,2012,21
2,51.505693,104.139224,505.79,5.0,-25.937000,1,3,94,2,2,1,0,0,2,12,9,2012,21
3,51.505724,104.139204,511.56,1.0,-25.937000,1,3,94,2,2,1,0,0,2,12,9,2012,21
4,51.505717,104.139202,514.92,1.0,-25.937000,1,3,94,2,2,1,0,0,2,12,9,2012,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2741,51.737582,103.428106,669.33,44.0,-29.246500,0,0,0,0,1,0,0,1,1,16,7,2022,9
2742,51.737811,103.427860,668.52,44.0,-29.246500,0,0,0,0,1,0,0,1,1,16,7,2022,9
2743,51.738017,103.427555,668.27,16.0,-29.246500,0,0,0,0,1,0,0,1,1,16,7,2022,9
2744,51.738100,103.427456,668.27,31.0,-29.207499,0,0,0,0,1,0,0,1,1,16,7,2022,9
2745,51.738253,103.427259,668.03,0.0,-29.207499,0,0,0,0,1,0,0,1,1,16,7,2022,9

In [21]:
def __temperature_forecast(row):
    params = {
    "latitude": row["latitude"],
    "longitude": row["longitude"],
    "start_date": str(pd.to_datetime(f"{int(row["date_year"])}-{int(row["date_month"])}-{int(row["date_day"])}").strftime("%Y-%m-%d")),
    "end_date": str(pd.to_datetime(f"{int(row["date_year"])}-{int(row["date_month"])}-{int(row["date_day"])}").strftime("%Y-%m-%d")),
    "hourly": ["temperature_2m"]
    }
    try:
        openmeteo = openmeteo_requests.Client()
        responses = openmeteo.weather_api("https://archive-api.open-meteo.com/v1/archive", params=params)
        response = responses[0]
        current = response.Hourly()
        temperatures = current.Variables(0).ValuesAsNumpy()
        return float(temperatures.mean())
    except Exception as e:
        print(f"Ошибка получения температуры на точке: {(row["latitude"], row["longitude"])}\n{e}")
        return None

In [31]:
points_predictions_flood = {}
points_predictions_fire = {}



for i in tqdm.tqdm(range(len(data.index.tolist()))):
    time_column = []
    temperature_column = []
    temperature_range = pd.DataFrame()
    predictions = []
    row = data.iloc[i]
    for k in range(4):
        row["date_year"] -= 1
        time_column.append(str(pd.to_datetime(f"{int(row["date_year"])}-{int(row["date_month"])}-{int(row["date_day"])}").strftime("%Y-%m-%d")))
        temperature_column.append(__temperature_forecast(row))
    temperature_range = pd.concat([temperature_range, pd.Series(temperature_column, name="temperature")], axis=1)
    temperature_range = pd.concat([temperature_range, pd.Series(time_column, name="time")], axis=1)
    temperature_range["time"] = pd.to_datetime(temperature_range["time"])
    temperature_range = temperature_range.set_index("time")
    temperature_range = temperature_range.iloc[::-1]
    model = ARIMA(temperature_range, order=(1,1,1))
    model_fit = model.fit()
    arima_predictions = model_fit.forecast(steps=10)
    
    for k, v in enumerate(arima_predictions):
        row = data.iloc[i]
        row["date_year"] += 1
        row["temperature"] = v
        model = load(r"C:\Users\demoexam\Desktop\Гурбанов\MachineLearning\Проект №6 (последний срез)\best_model.joblib")
        predict = model.predict(pd.DataFrame(row).T.drop("dangerous", axis=1))
        predictions.append(int(predict))
    points_predictions_flood[f"point_{i}"] = predictions
    print(points_predictions_flood)

  0%|          | 0/2746 [00:00<?, ?it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  0%|          | 1/2746 [00:03<2:41:36,  3.53s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  0%|          | 2/2746 [00:16<6:53:32,  9.04s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  0%|          | 3/2746 [00:20<5:01:17,  6.59s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  0%|          | 4/2746 [00:29<5:43:30,  7.52s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  0%|          | 5/2746 [00:36<5:34:13,  7.32s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  0%|          | 6/2746 [00:40<4:49:10,  6.33s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  0%|          | 7/2746 [00:47<4:56:25,  6.49s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  0%|          | 8/2746 [00:51<4:28:30,  5.88s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  0%|          | 9/2746 [01:05<6:24:11,  8.42s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  0%|          | 10/2746 [01:18<7:22:17,  9.70s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  0%|          | 11/2746 [01:23<6:17:10,  8.27s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  0%|          | 12/2746 [01:28<5:37:47,  7.41s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  0%|          | 13/2746 [01:32<4:42:00,  6.19s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 14/2746 [01:37<4:32:32,  5.99s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 15/2746 [01:44<4:36:39,  6.08s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 16/2746 [01:48<4:08:52,  5.47s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 17/2746 [01:53<4:11:22,  5.53s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 18/2746 [02:02<4:53:05,  6.45s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 19/2746 [02:05<4:12:38,  5.56s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 20/2746 [02:12<4:23:32,  5.80s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 21/2746 [02:19<4:41:17,  6.19s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 22/2746 [02:27<5:10:52,  6.85s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 23/2746 [02:33<4:58:12,  6.57s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 24/2746 [02:39<4:45:03,  6.28s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 25/2746 [02:46<4:56:56,  6.55s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 26/2746 [02:53<5:05:21,  6.74s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 27/2746 [02:59<4:52:48,  6.46s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 28/2746 [03:06<5:02:12,  6.67s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 29/2746 [03:13<4:59:45,  6.62s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 30/2746 [03:59<13:59:06, 18.54s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 31/2746 [04:08<11:56:33, 15.84s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 32/2746 [04:12<9:15:49, 12.29s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 33/2746 [04:18<7:41:12, 10.20s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|          | 34/2746 [04:24<6:42:25,  8.90s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|▏         | 35/2746 [04:29<5:48:08,  7.70s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|▏         | 36/2746 [04:32<4:47:49,  6.37s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|▏         | 37/2746 [04:38<4:46:44,  6.35s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_36': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|▏         | 38/2746 [04:47<5:18:37,  7.06s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_36': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_37': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|▏         | 39/2746 [04:51<4:43:40,  6.29s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_36': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_37': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_38': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
Ошибка получения температуры на точке: (np.float64(51.49308211170137), np.float64(104.13096397183836))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Read timed out. (read timeout=30)

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|▏         | 40/2746 [05:39<13:56:53, 18.56s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_36': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_37': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_38': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_39': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  1%|▏         | 41/2746 [05:45<11:18:09, 15.04s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_36': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_37': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_38': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_39': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_40': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  2%|▏         | 42/2746 [05:50<9:01:55, 12.03s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_36': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_37': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_38': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_39': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_40': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_41': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  2%|▏         | 43/2746 [05:59<8:19:45, 11.09s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_36': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_37': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_38': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_39': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_40': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_41': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_42': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  2%|▏         | 44/2746 [06:06<7:27:06,  9.93s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_36': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_37': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_38': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_39': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_40': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_41': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_42': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_43': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  2%|▏         | 45/2746 [06:11<6:17:08,  8.38s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_36': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_37': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_38': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_39': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_40': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_41': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_42': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_43': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_44': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  2%|▏         | 46/2746 [06:16<5:26:23,  7.25s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_36': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_37': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_38': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_39': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_40': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_41': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_42': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_43': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_44': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_45': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  2%|▏         | 47/2746 [06:19<4:32:49,  6.07s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_36': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_37': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_38': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_39': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_40': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_41': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_42': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_43': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_44': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_45': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_46': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  2%|▏         | 48/2746 [06:25<4:27:33,  5.95s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_36': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_37': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_38': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_39': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_40': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_41': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_42': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_43': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_44': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_45': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_46': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_47': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  2%|▏         | 49/2746 [06:29<4:05:20,  5.46s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_36': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_37': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_38': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_39': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_40': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_41': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_42': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_43': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_44': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_45': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_46': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_47': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_48': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  2%|▏         | 50/2746 [06:39<5:07:41,  6.85s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_36': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_37': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_38': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_39': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_40': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_41': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_42': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_43': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_44': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_45': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_46': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_47': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_48': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_49': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  2%|▏         | 51/2746 [06:43<4:29:31,  6.00s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_36': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_37': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_38': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_39': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_40': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_41': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_42': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_43': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_44': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_45': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_46': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_47': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_48': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_49': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_50': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  2%|▏         | 52/2746 [06:47<3:55:07,  5.24s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_36': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_37': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_38': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_39': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_40': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_41': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_42': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_43': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_44': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_45': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_46': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_47': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_48': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_49': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_50': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_51': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  2%|▏         | 53/2746 [06:59<5:27:42,  7.30s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_36': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_37': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_38': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_39': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_40': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_41': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_42': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_43': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_44': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_45': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_46': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_47': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_48': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_49': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_50': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_51': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_52': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency 365D will be used.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_7944\2323049110.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  2%|▏         | 54/2746 [07:06<5:29:49,  7.35s/it]

{'point_0': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_1': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_2': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_3': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_4': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_5': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_6': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_7': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_8': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_9': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_10': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_11': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'point_12': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_13': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_14': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_15': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_16': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_17': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_18': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_19': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_20': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_21': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_22': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_23': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_24': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_25': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_26': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_27': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_28': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_29': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_30': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_31': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_32': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_33': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_34': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_35': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_36': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_37': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_38': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_39': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_40': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_41': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_42': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_43': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_44': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_45': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_46': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_47': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_48': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_49': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_50': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_51': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_52': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'point_53': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

  2%|▏         | 54/2746 [07:12<5:59:17,  8.01s/it]

KeyboardInterrupt:

In [29]:
arima_predictions

2012-09-11    12.680752
2013-09-11     9.350417
2014-09-11    11.670818
2015-09-11    10.054085
2016-09-10    11.180539
2017-09-10    10.395686
2018-09-10    10.942530
2019-09-10    10.561518
2020-09-09    10.826987
2021-09-09    10.642022
Freq: 365D, Name: predicted_mean, dtype: float64

In [25]:
class ModelTraining():
    """
    Класс для обучения моделей машинного обучения на данных.

    Attributes:
        sql_path(str): Путь к папке с базой данных
    """
    
    def __init__(self, sql_path: str):
        """
        Инициализация класса и подготовка датасета к прогонке через модели.
    
        Attributes:
            sql_path(str): Путь к папке с базой данных
        """

        # Включение игнорирования мешающих предупреждений
        warnings.filterwarnings('ignore', category=pd.errors.SettingWithCopyWarning)
        # Загрузка базы данных
        try:
            con = sqlite3.connect(sql_path)
            self.data = pd.read_sql("SELECT * FROM Clear_data", con=con)
        except Exception as e:
            print(f"Ошибка в загрузке из базы данных: {e}")
            
        try:
            # Удаление не нужны в обучении колонок
            self.data = self.data.drop(["level_0", "index"], axis=1)
            self.data = self.data.drop(["country", "cluster_2", "point_id"], axis=1)
            # Подготовка колонки со временем, а именно разделение ее на
            # отдельные колонки (date_day, date_month, date_year, date_hour)
            self.data["time"] = pd.to_datetime(self.data["time"])
            self.data['date_day'] = self.data['time'].dt.day
            self.data['date_month'] = self.data['time'].dt.month
            self.data['date_year'] = self.data['time'].dt.year
            self.data['date_hour'] = self.data['time'].dt.hour
            self.data = self.data.drop("time", axis=1)
        except Exception as e:
            print(f"Ошибка в оптимизации данных: {e}")

            
    def fit_model(self, target: str):
        """
        Обучает 3 модели и оценивает их качество
        Args:
            target(str): Название столбца с предказываемыми данными
        """
        
        self.target = target
        X_train, X_test, y_train, y_test = train_test_split(self.data.drop(target, axis=1), self.data[target], test_size=0.33, random_state=42)
        LR = LogisticRegression(max_iter=5000)
        LR.fit(X_train, y_train)
        GBC = GradientBoostingClassifier()
        GBC.fit(X_train, y_train)
        MLPC = MLPClassifier()
        MLPC.fit(X_train, y_train)
        self.models = {"MLPClassifier": MLPC, "GradientBoostingClassifier": GBC, "LogisticRegression": LR}
        for name_model in self.models:
            model = self.models[name_model]
            model_pred = model.predict(X_test)
            model_proba = model.predict_proba(X_test)
            print(f"Модель {name_model}:\n\nТочность: {accuracy_score(y_test, model_pred)}\nПолнота: {recall_score(y_test, model_pred, average="micro")}\nF1-метрика: {f1_score(y_test, model_pred, average="micro")}\nROC-AUC метрика: {roc_auc_score(y_true=y_test, y_score=model_proba[:, 1], average="micro", multi_class="ovr")}\n\n")


    def save_model(self, model_name: str):
        """
        Сохраняет выбранную модель.
        Args:
            model_name(str): Имя выбранной модели
        """

        dump(self.models[model_name], f"{self.target}.joblib")

        
    def __temperature_forecast(self, row):
        """
        С помощью API запроса получается температуру в определенной точке в определенную дату
        Args:
            row(pd.Series): Колонка со всей информацией
        """

        params = {
        "latitude": row["latitude"],
        "longitude": row["longitude"],
        "start_date": str(pd.to_datetime(f"{int(row["date_year"])}-{int(row["date_month"])}-{int(row["date_day"])}").strftime("%Y-%m-%d")),
        "end_date": str(pd.to_datetime(f"{int(row["date_year"])}-{int(row["date_month"])}-{int(row["date_day"])}").strftime("%Y-%m-%d")),
        "hourly": ["temperature_2m"]
        }
        
        try:
            openmeteo = openmeteo_requests.Client()
            responses = openmeteo.weather_api("https://archive-api.open-meteo.com/v1/archive", params=params)
            response = responses[0]
            current = response.Hourly()
            temperatures = current.Variables(0).ValuesAsNumpy()
            return float(temperatures.mean())
        except Exception as e:
            print(f"Ошибка получения температуры на точке: {(row["latitude"], row["longitude"])}\n{e}")
            return 12

    def predictions(self, target: str, period: int, track: int):
        """
        Получение предсказание модели, на определенный срок вперед.
        Args:
            target(str): Колонка, которую будет предсказывать модель
            period(int): На сколько лет вперед будет предсказание
        """

        
        self.points_predictions_flood = {}
        data = self.data[self.data["track_id"] == track]
        try:
            model = load(f"C:\\Users\\demoexam\\Desktop\\Гурбанов\MachineLearning\\Проект №6 (последний срез)\\{target}.joblib")
        except Exception as e:
            return "Модели, обученной под этот target не было найдено!"
        for i in tqdm.tqdm(range(len(data.index.tolist()))):
            time_column = []
            temperature_column = []
            temperature_range = pd.DataFrame()
            predictions = []
            row = data.iloc[i]
            for k in range(4):
                row["date_year"] -= 1
                time_column.append(str(pd.to_datetime(f"{int(row["date_year"])}-{int(row["date_month"])}-{int(row["date_day"])}").strftime("%Y-%m-%d")))
                temperature_column.append(self.__temperature_forecast(row))
            temperature_range = pd.concat([temperature_range, pd.Series(temperature_column, name="temperature")], axis=1)
            temperature_range = pd.concat([temperature_range, pd.Series(time_column, name="time")], axis=1)
            temperature_range["time"] = pd.to_datetime(temperature_range["time"])
            temperature_range = temperature_range.set_index("time")
            temperature_range = temperature_range.iloc[::-1]
            model = ARIMA(temperature_range, order=(1,1,1))
            model_fit = model.fit()
            arima_predictions = model_fit.forecast(steps=period)
            
            for k, v in enumerate(arima_predictions):
                row = data.iloc[i]
                row["date_year"] += 1
                row["temperature"] = v
                model = load(f"C:\\Users\\demoexam\\Desktop\\Гурбанов\MachineLearning\\Проект №6 (последний срез)\\{target}.joblib")
                predict = model.predict(pd.DataFrame(row).T.drop(target, axis=1))
                predictions.append(int(predict))
            self.points_predictions_flood[f"point_{i}"] = predictions
            
        return self.points_predictions_flood

In [26]:
agent = ModelTraining(r"C:\Users\demoexam\Desktop\Гурбанов\MachineLearning\Проект №6 (последний срез)\clear_data.db")

In [27]:
agent.fit_model("flood")

Модель MLPClassifier:

Точность: 1.0
Полнота: 1.0
F1-метрика: 1.0
ROC-AUC метрика: 1.0


Модель GradientBoostingClassifier:

Точность: 1.0
Полнота: 1.0
F1-метрика: 1.0
ROC-AUC метрика: 1.0


Модель LogisticRegression:

Точность: 1.0
Полнота: 1.0
F1-метрика: 1.0
ROC-AUC метрика: 1.0

In [28]:
agent.save_model("LogisticRegression")

In [29]:
agent.fit_model("fire")

Модель MLPClassifier:

Точность: 1.0
Полнота: 1.0
F1-метрика: 1.0
ROC-AUC метрика: 1.0


Модель GradientBoostingClassifier:

Точность: 1.0
Полнота: 1.0
F1-метрика: 1.0
ROC-AUC метрика: 1.0


Модель LogisticRegression:

Точность: 1.0
Полнота: 1.0
F1-метрика: 1.0
ROC-AUC метрика: 1.0

In [30]:
agent.save_model("LogisticRegression")

In [31]:
agent.predictions("flood", 10, 2)

  0%|          | 0/744 [00:00<?, ?it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  0%|          | 1/744 [00:02<34:18,  2.77s/it]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  0%|          | 2/744 [00:05<32:00,  2.59s/it]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
  0%|          | 3/744 [00:07<32:04,  2.60s/it]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)

Ошибка получения температуры на точке: (np.float64(51.705434108152986), np.float64(103.42430767603219))
failed to request 'https://archive-api.open-meteo.com/v1/archive': ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Ошибка получения температуры на точке: (np.float64(51.705434108152986), np.float64(103.42430767603219))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.705434108152986&longitude=103.42430767603219&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF4CD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70562110841274), np.float64(103.42423123307526))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70562110841274&longitude=103.42423123307526&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDFD90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70562110841274), np.float64(103.42423123307526))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70562110841274&longitude=103.42423123307526&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552D38190>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70562110841274), np.float64(103.42423123307526))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70562110841274&longitude=103.42423123307526&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DC0E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70562110841274), np.float64(103.42423123307526))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70562110841274&longitude=103.42423123307526&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF47D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70580567792058), np.float64(103.42412604019046))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70580567792058&longitude=103.42412604019046&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF4050>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70580567792058), np.float64(103.42412604019046))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70580567792058&longitude=103.42412604019046&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF6D50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70580567792058), np.float64(103.42412604019046))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70580567792058&longitude=103.42412604019046&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF6C10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70580567792058), np.float64(103.42412604019046))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70580567792058&longitude=103.42412604019046&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEC050>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 81%|████████  | 604/744 [30:35<03:20,  1.43s/it]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 81%|████████▏ | 605/744 [30:35<02:24,  1.04s/it]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.705983290448785), np.float64(103.42405227944255))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.705983290448785&longitude=103.42405227944255&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF4B90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.705983290448785), np.float64(103.42405227944255))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.705983290448785&longitude=103.42405227944255&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF7ED0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.705983290448785), np.float64(103.42405227944255))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.705983290448785&longitude=103.42405227944255&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5810>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.705983290448785), np.float64(103.42405227944255))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.705983290448785&longitude=103.42405227944255&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF6E90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.706206584349275), np.float64(103.42398446984589))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.706206584349275&longitude=103.42398446984589&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DC0A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.706206584349275), np.float64(103.42398446984589))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.706206584349275&longitude=103.42398446984589&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDF4D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.706206584349275), np.float64(103.42398446984589))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.706206584349275&longitude=103.42398446984589&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDC410>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.706206584349275), np.float64(103.42398446984589))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.706206584349275&longitude=103.42398446984589&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEC410>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 81%|████████▏ | 606/744 [30:35<01:45,  1.31it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 82%|████████▏ | 607/744 [30:35<01:17,  1.77it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.70642233453691), np.float64(103.42397944070399))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70642233453691&longitude=103.42397944070399&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DC0E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70642233453691), np.float64(103.42397944070399))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70642233453691&longitude=103.42397944070399&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDE850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70642233453691), np.float64(103.42397944070399))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70642233453691&longitude=103.42397944070399&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDCB90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70642233453691), np.float64(103.42397944070399))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70642233453691&longitude=103.42397944070399&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF42D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70660799369216), np.float64(103.42403886839747))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70660799369216&longitude=103.42403886839747&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF7ED0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70660799369216), np.float64(103.42403886839747))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70660799369216&longitude=103.42403886839747&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF4B90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70660799369216), np.float64(103.42403886839747))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70660799369216&longitude=103.42403886839747&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DECE10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70660799369216), np.float64(103.42403886839747))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70660799369216&longitude=103.42403886839747&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEC410>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 82%|████████▏ | 608/744 [30:36<00:58,  2.33it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 82%|████████▏ | 609/744 [30:36<00:44,  3.00it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.706753419712186), np.float64(103.42412712983787))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.706753419712186&longitude=103.42412712983787&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5450>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.706753419712186), np.float64(103.42412712983787))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.706753419712186&longitude=103.42412712983787&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.706753419712186), np.float64(103.42412712983787))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.706753419712186&longitude=103.42412712983787&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF4550>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.706753419712186), np.float64(103.42412712983787))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.706753419712186&longitude=103.42412712983787&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF6AD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70689188875258), np.float64(103.42424313537776))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70689188875258&longitude=103.42424313537776&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDE850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70689188875258), np.float64(103.42424313537776))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70689188875258&longitude=103.42424313537776&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DED950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70689188875258), np.float64(103.42424313537776))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70689188875258&longitude=103.42424313537776&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEC690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70689188875258), np.float64(103.42424313537776))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70689188875258&longitude=103.42424313537776&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DED1D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 82%|████████▏ | 610/744 [30:36<00:35,  3.77it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.70789738185704), np.float64(103.42396611347795))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70789738185704&longitude=103.42396611347795&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DC3610>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70789738185704), np.float64(103.42396611347795))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70789738185704&longitude=103.42396611347795&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDE850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70789738185704), np.float64(103.42396611347795))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70789738185704&longitude=103.42396611347795&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF42D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70789738185704), np.float64(103.42396611347795))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70789738185704&longitude=103.42396611347795&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF7ED0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 82%|████████▏ | 611/744 [50:07<12:59:13, 351.53s/it]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 82%|████████▏ | 612/744 [50:07<9:01:26, 246.11s/it] C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.70802420005202), np.float64(103.4236919414252))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70802420005202&longitude=103.4236919414252&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DECB90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70802420005202), np.float64(103.4236919414252))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70802420005202&longitude=103.4236919414252&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEC050>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70802420005202), np.float64(103.4236919414252))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70802420005202&longitude=103.4236919414252&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DED310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70802420005202), np.float64(103.4236919414252))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70802420005202&longitude=103.4236919414252&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEC2D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70819896273315), np.float64(103.42352413572371))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70819896273315&longitude=103.42352413572371&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70819896273315), np.float64(103.42352413572371))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70819896273315&longitude=103.42352413572371&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF4A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70819896273315), np.float64(103.42352413572371))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70819896273315&longitude=103.42352413572371&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF56D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70819896273315), np.float64(103.42352413572371))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70819896273315&longitude=103.42352413572371&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DC0A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 82%|████████▏ | 613/744 [50:07<6:16:12, 172.31s/it]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 83%|████████▎ | 614/744 [50:07<4:21:24, 120.65s/it]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.70829669572413), np.float64(103.42340310104191))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70829669572413&longitude=103.42340310104191&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DED590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70829669572413), np.float64(103.42340310104191))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70829669572413&longitude=103.42340310104191&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DED950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70829669572413), np.float64(103.42340310104191))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70829669572413&longitude=103.42340310104191&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DECA50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70829669572413), np.float64(103.42340310104191))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70829669572413&longitude=103.42340310104191&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEC190>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.708390824496746), np.float64(103.42314049601555))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.708390824496746&longitude=103.42314049601555&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDC410>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.708390824496746), np.float64(103.42314049601555))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.708390824496746&longitude=103.42314049601555&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF6AD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.708390824496746), np.float64(103.42314049601555))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.708390824496746&longitude=103.42314049601555&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF42D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.708390824496746), np.float64(103.42314049601555))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.708390824496746&longitude=103.42314049601555&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF7ED0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 83%|████████▎ | 615/744 [50:07<3:01:39, 84.49s/it] C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 83%|████████▎ | 616/744 [50:07<2:06:14, 59.17s/it]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))

Ошибка получения температуры на точке: (np.float64(51.70858486555517), np.float64(103.42285660095513))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70858486555517&longitude=103.42285660095513&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEE0D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70858486555517), np.float64(103.42285660095513))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70858486555517&longitude=103.42285660095513&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DECB90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70858486555517), np.float64(103.42285660095513))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70858486555517&longitude=103.42285660095513&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEDD10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70858486555517), np.float64(103.42285660095513))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70858486555517&longitude=103.42285660095513&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DED1D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70872668735683), np.float64(103.4227405115962))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70872668735683&longitude=103.4227405115962&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF4A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70872668735683), np.float64(103.4227405115962))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70872668735683&longitude=103.4227405115962&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF56D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70872668735683), np.float64(103.4227405115962))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70872668735683&longitude=103.4227405115962&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF6AD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70872668735683), np.float64(103.4227405115962))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70872668735683&longitude=103.4227405115962&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDC410>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70884260907769), np.float64(103.42259550467134))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70884260907769&longitude=103.42259550467134&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEE850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70884260907769), np.float64(103.42259550467134))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70884260907769&longitude=103.42259550467134&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DED590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70884260907769), np.float64(103.42259550467134))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70884260907769&longitude=103.42259550467134&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEE490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 83%|████████▎ | 618/744 [50:08<1:07:00, 31.91s/it]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))

Ошибка получения температуры на точке: (np.float64(51.70884260907769), np.float64(103.42259550467134))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70884260907769&longitude=103.42259550467134&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DECE10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70901167206466), np.float64(103.42244421131909))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70901167206466&longitude=103.42244421131909&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DED1D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70901167206466), np.float64(103.42244421131909))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70901167206466&longitude=103.42244421131909&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEE0D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70901167206466), np.float64(103.42244421131909))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70901167206466&longitude=103.42244421131909&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEEC10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70901167206466), np.float64(103.42244421131909))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70901167206466&longitude=103.42244421131909&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DED310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70915458351374), np.float64(103.42227883636951))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70915458351374&longitude=103.42227883636951&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEF9D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70915458351374), np.float64(103.42227883636951))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70915458351374&longitude=103.42227883636951&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF7D90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70915458351374), np.float64(103.42227883636951))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70915458351374&longitude=103.42227883636951&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF6210>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70915458351374), np.float64(103.42227883636951))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70915458351374&longitude=103.42227883636951&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 83%|████████▎ | 620/744 [50:08<39:49, 19.27s/it]  C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 83%|████████▎ | 621/744 [50:08<30:49, 15.03s/it]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))

Ошибка получения температуры на точке: (np.float64(51.70935021713376), np.float64(103.42207021079957))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70935021713376&longitude=103.42207021079957&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552D3AAD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70935021713376), np.float64(103.42207021079957))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70935021713376&longitude=103.42207021079957&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEF9D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70935021713376), np.float64(103.42207021079957))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70935021713376&longitude=103.42207021079957&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DED310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70935021713376), np.float64(103.42207021079957))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70935021713376&longitude=103.42207021079957&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEEC10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70954157598317), np.float64(103.42180483974516))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70954157598317&longitude=103.42180483974516&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552D256D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70954157598317), np.float64(103.42180483974516))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70954157598317&longitude=103.42180483974516&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF42D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70954157598317), np.float64(103.42180483974516))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70954157598317&longitude=103.42180483974516&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF4550>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70954157598317), np.float64(103.42180483974516))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70954157598317&longitude=103.42180483974516&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF6E90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 84%|████████▎ | 622/744 [50:08<23:16, 11.45s/it]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 84%|████████▎ | 623/744 [50:08<17:14,  8.55s/it]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))

Ошибка получения температуры на точке: (np.float64(51.70965020544827), np.float64(103.42166704125702))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70965020544827&longitude=103.42166704125702&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF6E90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70965020544827), np.float64(103.42166704125702))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70965020544827&longitude=103.42166704125702&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF4550>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70965020544827), np.float64(103.42166704125702))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70965020544827&longitude=103.42166704125702&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF42D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.70965020544827), np.float64(103.42166704125702))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.70965020544827&longitude=103.42166704125702&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEC690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.709772078320384), np.float64(103.42156302183867))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.709772078320384&longitude=103.42156302183867&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF6AD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.709772078320384), np.float64(103.42156302183867))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.709772078320384&longitude=103.42156302183867&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DED590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.709772078320384), np.float64(103.42156302183867))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.709772078320384&longitude=103.42156302183867&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEEFD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.709772078320384), np.float64(103.42156302183867))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.709772078320384&longitude=103.42156302183867&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDF9D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71016870997846), np.float64(103.42121131718159))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71016870997846&longitude=103.42121131718159&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DC0A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71016870997846), np.float64(103.42121131718159))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71016870997846&longitude=103.42121131718159&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEF390>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71016870997846), np.float64(103.42121131718159))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71016870997846&longitude=103.42121131718159&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEE990>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 84%|████████▍ | 625/744 [50:08<09:53,  4.99s/it]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 84%|████████▍ | 626/744 [50:09<07:35,  3.86s/it]

Ошибка получения температуры на точке: (np.float64(51.71016870997846), np.float64(103.42121131718159))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71016870997846&longitude=103.42121131718159&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEF9D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.710320841521025), np.float64(103.42107368633151))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.710320841521025&longitude=103.42107368633151&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDE210>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.710320841521025), np.float64(103.42107368633151))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.710320841521025&longitude=103.42107368633151&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.710320841521025), np.float64(103.42107368633151))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.710320841521025&longitude=103.42107368633151&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF56D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.710320841521025), np.float64(103.42107368633151))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.710320841521025&longitude=103.42107368633151&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E00690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71054447069764), np.float64(103.42087218537927))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71054447069764&longitude=103.42087218537927&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF7610>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71054447069764), np.float64(103.42087218537927))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71054447069764&longitude=103.42087218537927&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF4550>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71054447069764), np.float64(103.42087218537927))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71054447069764&longitude=103.42087218537927&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF42D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 84%|████████▍ | 627/744 [50:09<05:42,  2.93s/it]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 84%|████████▍ | 628/744 [50:09<04:13,  2.19s/it]

Ошибка получения температуры на точке: (np.float64(51.71054447069764), np.float64(103.42087218537927))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71054447069764&longitude=103.42087218537927&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF6490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71078042127192), np.float64(103.4205871168524))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71078042127192&longitude=103.4205871168524&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEE850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71078042127192), np.float64(103.4205871168524))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71078042127192&longitude=103.4205871168524&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DECA50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71078042127192), np.float64(103.4205871168524))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71078042127192&longitude=103.4205871168524&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DC2210>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71078042127192), np.float64(103.4205871168524))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71078042127192&longitude=103.4205871168524&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E007D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7109732888639), np.float64(103.42023683711886))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7109732888639&longitude=103.42023683711886&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DA3750>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7109732888639), np.float64(103.42023683711886))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7109732888639&longitude=103.42023683711886&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DECB90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7109732888639), np.float64(103.42023683711886))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7109732888639&longitude=103.42023683711886&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEF390>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7109732888639), np.float64(103.42023683711886))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7109732888639&longitude=103.42023683711886&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DED310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 85%|████████▍ | 630/744 [50:09<02:27,  1.29s/it]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))

Ошибка получения температуры на точке: (np.float64(51.711171772331), np.float64(103.42003307305276))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.711171772331&longitude=103.42003307305276&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF7D90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.711171772331), np.float64(103.42003307305276))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.711171772331&longitude=103.42003307305276&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF7610>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.711171772331), np.float64(103.42003307305276))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.711171772331&longitude=103.42003307305276&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E01310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.711171772331), np.float64(103.42003307305276))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.711171772331&longitude=103.42003307305276&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E007D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71135080978274), np.float64(103.41993198730052))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71135080978274&longitude=103.41993198730052&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71135080978274), np.float64(103.41993198730052))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71135080978274&longitude=103.41993198730052&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF7610>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71135080978274), np.float64(103.41993198730052))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71135080978274&longitude=103.41993198730052&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDE210>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71135080978274), np.float64(103.41993198730052))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71135080978274&longitude=103.41993198730052&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DC2210>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 85%|████████▍ | 632/744 [50:09<01:34,  1.19it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 85%|████████▌ | 633/744 [50:09<01:16,  1.46it/s]

Ошибка получения температуры на точке: (np.float64(51.71154862269759), np.float64(103.41990030370653))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71154862269759&longitude=103.41990030370653&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DECB90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71154862269759), np.float64(103.41990030370653))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71154862269759&longitude=103.41990030370653&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E01D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71154862269759), np.float64(103.41990030370653))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71154862269759&longitude=103.41990030370653&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E00A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71154862269759), np.float64(103.41990030370653))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71154862269759&longitude=103.41990030370653&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E016D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.711890269070864), np.float64(103.41975186020136))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.711890269070864&longitude=103.41975186020136&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEEC10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.711890269070864), np.float64(103.41975186020136))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.711890269070864&longitude=103.41975186020136&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DECB90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.711890269070864), np.float64(103.41975186020136))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.711890269070864&longitude=103.41975186020136&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DC2210>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.711890269070864), np.float64(103.41975186020136))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.711890269070864&longitude=103.41975186020136&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF6D50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 85%|████████▌ | 634/744 [50:09<01:00,  1.82it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.711993869394064), np.float64(103.41965253464878))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.711993869394064&longitude=103.41965253464878&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E00F50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.711993869394064), np.float64(103.41965253464878))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.711993869394064&longitude=103.41965253464878&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E00690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.711993869394064), np.float64(103.41965253464878))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.711993869394064&longitude=103.41965253464878&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E011D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.711993869394064), np.float64(103.41965253464878))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.711993869394064&longitude=103.41965253464878&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E00050>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71216418966651), np.float64(103.41950308531523))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71216418966651&longitude=103.41950308531523&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71216418966651), np.float64(103.41950308531523))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71216418966651&longitude=103.41950308531523&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF7610>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71216418966651), np.float64(103.41950308531523))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71216418966651&longitude=103.41950308531523&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DC0A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71216418966651), np.float64(103.41950308531523))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71216418966651&longitude=103.41950308531523&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEEFD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 85%|████████▌ | 635/744 [50:09<00:47,  2.28it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 85%|████████▌ | 636/744 [50:10<00:37,  2.84it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.71237449161708), np.float64(103.41937978751957))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71237449161708&longitude=103.41937978751957&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E01950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71237449161708), np.float64(103.41937978751957))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71237449161708&longitude=103.41937978751957&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E01D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71237449161708), np.float64(103.41937978751957))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71237449161708&longitude=103.41937978751957&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E00E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71237449161708), np.float64(103.41937978751957))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71237449161708&longitude=103.41937978751957&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E002D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71270691789687), np.float64(103.41933527961373))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71270691789687&longitude=103.41933527961373&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEE990>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71270691789687), np.float64(103.41933527961373))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71270691789687&longitude=103.41933527961373&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552D256D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71270691789687), np.float64(103.41933527961373))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71270691789687&longitude=103.41933527961373&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDF9D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71270691789687), np.float64(103.41933527961373))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71270691789687&longitude=103.41933527961373&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF7610>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 86%|████████▌ | 637/744 [50:10<00:30,  3.48it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 86%|████████▌ | 638/744 [50:10<00:25,  4.22it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.71282183378935), np.float64(103.41933787800372))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71282183378935&longitude=103.41933787800372&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E02490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71282183378935), np.float64(103.41933787800372))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71282183378935&longitude=103.41933787800372&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E00F50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71282183378935), np.float64(103.41933787800372))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71282183378935&longitude=103.41933787800372&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E020D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71282183378935), np.float64(103.41933787800372))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71282183378935&longitude=103.41933787800372&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E016D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.713044038042426), np.float64(103.41936629265547))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.713044038042426&longitude=103.41936629265547&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF4550>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.713044038042426), np.float64(103.41936629265547))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.713044038042426&longitude=103.41936629265547&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF7610>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.713044038042426), np.float64(103.41936629265547))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.713044038042426&longitude=103.41936629265547&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DC2210>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.713044038042426), np.float64(103.41936629265547))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.713044038042426&longitude=103.41936629265547&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEE850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 86%|████████▌ | 639/744 [50:10<00:21,  4.99it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 86%|████████▌ | 641/744 [50:10<00:15,  6.44it/s]

Ошибка получения температуры на точке: (np.float64(51.71331980265677), np.float64(103.41941767372191))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71331980265677&longitude=103.41941767372191&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E02C10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71331980265677), np.float64(103.41941767372191))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71331980265677&longitude=103.41941767372191&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E01950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71331980265677), np.float64(103.41941767372191))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71331980265677&longitude=103.41941767372191&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E02850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71331980265677), np.float64(103.41941767372191))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71331980265677&longitude=103.41941767372191&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E01310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71357813291252), np.float64(103.41946821659803))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71357813291252&longitude=103.41946821659803&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E016D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71357813291252), np.float64(103.41946821659803))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71357813291252&longitude=103.41946821659803&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E01310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71357813291252), np.float64(103.41946821659803))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71357813291252&longitude=103.41946821659803&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E02850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71357813291252), np.float64(103.41946821659803))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71357813291252&longitude=103.41946821659803&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E01950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71382900327444), np.float64(103.41965773142874))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71382900327444&longitude=103.41965773142874&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E03C50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71382900327444), np.float64(103.41965773142874))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71382900327444&longitude=103.41965773142874&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DC0A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71382900327444), np.float64(103.41965773142874))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71382900327444&longitude=103.41965773142874&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 86%|████████▋ | 642/744 [50:10<00:14,  7.02it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 86%|████████▋ | 643/744 [50:10<00:13,  7.44it/s]

Ошибка получения температуры на точке: (np.float64(51.71382900327444), np.float64(103.41965773142874))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71382900327444&longitude=103.41965773142874&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF4550>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.714030504226685), np.float64(103.41994137503207))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.714030504226685&longitude=103.41994137503207&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEC190>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.714030504226685), np.float64(103.41994137503207))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.714030504226685&longitude=103.41994137503207&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF7D90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.714030504226685), np.float64(103.41994137503207))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.714030504226685&longitude=103.41994137503207&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DC2210>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.714030504226685), np.float64(103.41994137503207))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.714030504226685&longitude=103.41994137503207&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DA3750>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71424390748143), np.float64(103.42020339332521))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71424390748143&longitude=103.42020339332521&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E020D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71424390748143), np.float64(103.42020339332521))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71424390748143&longitude=103.42020339332521&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E00F50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71424390748143), np.float64(103.42020339332521))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71424390748143&longitude=103.42020339332521&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E025D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71424390748143), np.float64(103.42020339332521))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71424390748143&longitude=103.42020339332521&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 87%|████████▋ | 644/744 [50:10<00:12,  7.83it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 87%|████████▋ | 645/744 [50:11<00:12,  8.14it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.7144008167088), np.float64(103.42039676383138))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7144008167088&longitude=103.42039676383138&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E01950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7144008167088), np.float64(103.42039676383138))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7144008167088&longitude=103.42039676383138&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E011D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7144008167088), np.float64(103.42039676383138))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7144008167088&longitude=103.42039676383138&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E025D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7144008167088), np.float64(103.42039676383138))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7144008167088&longitude=103.42039676383138&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E00F50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.714597288519144), np.float64(103.42064931057394))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.714597288519144&longitude=103.42064931057394&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF4550>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.714597288519144), np.float64(103.42064931057394))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.714597288519144&longitude=103.42064931057394&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552D256D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.714597288519144), np.float64(103.42064931057394))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.714597288519144&longitude=103.42064931057394&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20410>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.714597288519144), np.float64(103.42064931057394))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.714597288519144&longitude=103.42064931057394&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E202D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 87%|████████▋ | 646/744 [50:11<00:11,  8.37it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 87%|████████▋ | 647/744 [50:11<00:11,  8.44it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.71475646086037), np.float64(103.42081921175122))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71475646086037&longitude=103.42081921175122&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEE850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71475646086037), np.float64(103.42081921175122))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71475646086037&longitude=103.42081921175122&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF6E90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71475646086037), np.float64(103.42081921175122))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71475646086037&longitude=103.42081921175122&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF4550>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71475646086037), np.float64(103.42081921175122))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71475646086037&longitude=103.42081921175122&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E02850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71491479501128), np.float64(103.42098366469145))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71491479501128&longitude=103.42098366469145&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E011D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71491479501128), np.float64(103.42098366469145))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71491479501128&longitude=103.42098366469145&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E03C50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71491479501128), np.float64(103.42098366469145))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71491479501128&longitude=103.42098366469145&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71491479501128), np.float64(103.42098366469145))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71491479501128&longitude=103.42098366469145&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 87%|████████▋ | 648/744 [50:11<00:11,  8.53it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 87%|████████▋ | 649/744 [50:11<00:10,  8.69it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.715139765292406), np.float64(103.42117041349411))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.715139765292406&longitude=103.42117041349411&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E02490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.715139765292406), np.float64(103.42117041349411))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.715139765292406&longitude=103.42117041349411&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E03B10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.715139765292406), np.float64(103.42117041349411))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.715139765292406&longitude=103.42117041349411&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E01D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.715139765292406), np.float64(103.42117041349411))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.715139765292406&longitude=103.42117041349411&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF7D90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71531427651644), np.float64(103.42139446176589))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71531427651644&longitude=103.42139446176589&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDF9D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71531427651644), np.float64(103.42139446176589))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71531427651644&longitude=103.42139446176589&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71531427651644), np.float64(103.42139446176589))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71531427651644&longitude=103.42139446176589&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71531427651644), np.float64(103.42139446176589))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71531427651644&longitude=103.42139446176589&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 87%|████████▋ | 650/744 [50:11<00:10,  8.76it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 88%|████████▊ | 651/744 [50:11<00:10,  8.89it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.715397760272026), np.float64(103.42151851393282))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.715397760272026&longitude=103.42151851393282&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DECB90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.715397760272026), np.float64(103.42151851393282))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.715397760272026&longitude=103.42151851393282&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF6E90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.715397760272026), np.float64(103.42151851393282))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.715397760272026&longitude=103.42151851393282&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E02850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.715397760272026), np.float64(103.42151851393282))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.715397760272026&longitude=103.42151851393282&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E01D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71608205884695), np.float64(103.42256331816316))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71608205884695&longitude=103.42256331816316&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71608205884695), np.float64(103.42256331816316))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71608205884695&longitude=103.42256331816316&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71608205884695), np.float64(103.42256331816316))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71608205884695&longitude=103.42256331816316&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E202D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71608205884695), np.float64(103.42256331816316))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71608205884695&longitude=103.42256331816316&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E220D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 88%|████████▊ | 652/744 [50:11<00:10,  9.10it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 88%|████████▊ | 653/744 [50:11<00:10,  9.09it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'

Ошибка получения температуры на точке: (np.float64(51.71623511239886), np.float64(103.4228631388396))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71623511239886&longitude=103.4228631388396&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E01950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71623511239886), np.float64(103.4228631388396))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71623511239886&longitude=103.4228631388396&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E011D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71623511239886), np.float64(103.4228631388396))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71623511239886&longitude=103.4228631388396&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E02FD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71623511239886), np.float64(103.4228631388396))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71623511239886&longitude=103.4228631388396&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF6E90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.716377437114716), np.float64(103.42310386709869))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.716377437114716&longitude=103.42310386709869&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21A90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.716377437114716), np.float64(103.42310386709869))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.716377437114716&longitude=103.42310386709869&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.716377437114716), np.float64(103.42310386709869))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.716377437114716&longitude=103.42310386709869&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.716377437114716), np.float64(103.42310386709869))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.716377437114716&longitude=103.42310386709869&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 88%|████████▊ | 654/744 [50:12<00:09,  9.05it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 88%|████████▊ | 655/744 [50:12<00:09,  9.06it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 88%|████████▊ | 656/744 [50:12<00:09,  9.18it/s]

Ошибка получения температуры на точке: (np.float64(51.716483468189836), np.float64(103.42333269305527))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.716483468189836&longitude=103.42333269305527&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEC190>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.716483468189836), np.float64(103.42333269305527))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.716483468189836&longitude=103.42333269305527&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.716483468189836), np.float64(103.42333269305527))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.716483468189836&longitude=103.42333269305527&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E02FD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.716483468189836), np.float64(103.42333269305527))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.716483468189836&longitude=103.42333269305527&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E01D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71657809987664), np.float64(103.42354190535843))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71657809987664&longitude=103.42354190535843&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E22850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71657809987664), np.float64(103.42354190535843))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71657809987664&longitude=103.42354190535843&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71657809987664), np.float64(103.42354190535843))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71657809987664&longitude=103.42354190535843&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E22490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71657809987664), np.float64(103.42354190535843))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71657809987664&longitude=103.42354190535843&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 88%|████████▊ | 657/744 [50:12<00:09,  8.86it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'

Ошибка получения температуры на точке: (np.float64(51.71743799932301), np.float64(103.42501410283148))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71743799932301&longitude=103.42501410283148&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71743799932301), np.float64(103.42501410283148))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71743799932301&longitude=103.42501410283148&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71743799932301), np.float64(103.42501410283148))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71743799932301&longitude=103.42501410283148&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E22490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71743799932301), np.float64(103.42501410283148))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71743799932301&longitude=103.42501410283148&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71754562295973), np.float64(103.42526271007955))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71754562295973&longitude=103.42526271007955&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E23B10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71754562295973), np.float64(103.42526271007955))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71754562295973&longitude=103.42526271007955&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E02850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71754562295973), np.float64(103.42526271007955))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71754562295973&longitude=103.42526271007955&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEE850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71754562295973), np.float64(103.42526271007955))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71754562295973&longitude=103.42526271007955&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 88%|████████▊ | 658/744 [50:12<00:09,  8.72it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 89%|████████▊ | 659/744 [50:12<00:09,  8.88it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 89%|████████▊ | 660/744 [50:12<00:09,  9.07it/s]

Ошибка получения температуры на точке: (np.float64(51.71764327213168), np.float64(103.42548189684749))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71764327213168&longitude=103.42548189684749&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDE210>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71764327213168), np.float64(103.42548189684749))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71764327213168&longitude=103.42548189684749&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552D256D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71764327213168), np.float64(103.42548189684749))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71764327213168&longitude=103.42548189684749&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E02490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71764327213168), np.float64(103.42548189684749))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71764327213168&longitude=103.42548189684749&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E22850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71774720773101), np.float64(103.42569219879806))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71774720773101&longitude=103.42569219879806&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF4550>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71774720773101), np.float64(103.42569219879806))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71774720773101&longitude=103.42569219879806&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E22990>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71774720773101), np.float64(103.42569219879806))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71774720773101&longitude=103.42569219879806&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20410>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71774720773101), np.float64(103.42569219879806))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71774720773101&longitude=103.42569219879806&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3C690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 89%|████████▉ | 661/744 [50:12<00:09,  9.08it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 89%|████████▉ | 662/744 [50:12<00:08,  9.25it/s]

Ошибка получения температуры на точке: (np.float64(51.71785374172032), np.float64(103.4259920194745))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71785374172032&longitude=103.4259920194745&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E23890>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71785374172032), np.float64(103.4259920194745))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71785374172032&longitude=103.4259920194745&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71785374172032), np.float64(103.4259920194745))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71785374172032&longitude=103.4259920194745&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E22490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71785374172032), np.float64(103.4259920194745))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71785374172032&longitude=103.4259920194745&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.717996736988425), np.float64(103.42629083432257))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.717996736988425&longitude=103.42629083432257&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E01D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.717996736988425), np.float64(103.42629083432257))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.717996736988425&longitude=103.42629083432257&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF7D90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.717996736988425), np.float64(103.42629083432257))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.717996736988425&longitude=103.42629083432257&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553DEE850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.717996736988425), np.float64(103.42629083432257))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.717996736988425&longitude=103.42629083432257&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3C7D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 89%|████████▉ | 663/744 [50:13<00:08,  9.31it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.71808457933366), np.float64(103.42659903690219))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71808457933366&longitude=103.42659903690219&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E020D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71808457933366), np.float64(103.42659903690219))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71808457933366&longitude=103.42659903690219&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E01D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71808457933366), np.float64(103.42659903690219))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71808457933366&longitude=103.42659903690219&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71808457933366), np.float64(103.42659903690219))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71808457933366&longitude=103.42659903690219&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71814509667456), np.float64(103.42675519175828))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71814509667456&longitude=103.42675519175828&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71814509667456), np.float64(103.42675519175828))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71814509667456&longitude=103.42675519175828&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E23890>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71814509667456), np.float64(103.42675519175828))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71814509667456&longitude=103.42675519175828&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D1D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71814509667456), np.float64(103.42675519175828))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71814509667456&longitude=103.42675519175828&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3C7D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 89%|████████▉ | 664/744 [50:13<00:08,  9.18it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 90%|████████▉ | 666/744 [50:13<00:08,  9.42it/s]

Ошибка получения температуры на точке: (np.float64(51.718332432210445), np.float64(103.42711008153856))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.718332432210445&longitude=103.42711008153856&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20410>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.718332432210445), np.float64(103.42711008153856))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.718332432210445&longitude=103.42711008153856&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E23ED0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.718332432210445), np.float64(103.42711008153856))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.718332432210445&longitude=103.42711008153856&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21A90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.718332432210445), np.float64(103.42711008153856))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.718332432210445&longitude=103.42711008153856&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E22990>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71856419183314), np.float64(103.42729289084673))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71856419183314&longitude=103.42729289084673&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E01D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71856419183314), np.float64(103.42729289084673))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71856419183314&longitude=103.42729289084673&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3DD10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71856419183314), np.float64(103.42729289084673))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71856419183314&longitude=103.42729289084673&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3CA50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71856419183314), np.float64(103.42729289084673))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71856419183314&longitude=103.42729289084673&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 90%|████████▉ | 667/744 [50:13<00:08,  9.35it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.71877030283213), np.float64(103.42741283588111))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71877030283213&longitude=103.42741283588111&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E00F50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71877030283213), np.float64(103.42741283588111))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71877030283213&longitude=103.42741283588111&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71877030283213), np.float64(103.42741283588111))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71877030283213&longitude=103.42741283588111&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71877030283213), np.float64(103.42741283588111))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71877030283213&longitude=103.42741283588111&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71900801360607), np.float64(103.42766026966274))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71900801360607&longitude=103.42766026966274&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3CF50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71900801360607), np.float64(103.42766026966274))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71900801360607&longitude=103.42766026966274&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3C690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71900801360607), np.float64(103.42766026966274))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71900801360607&longitude=103.42766026966274&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D6D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71900801360607), np.float64(103.42766026966274))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71900801360607&longitude=103.42766026966274&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3C050>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 90%|████████▉ | 668/744 [50:13<00:08,  9.28it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 90%|████████▉ | 669/744 [50:13<00:08,  9.28it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 90%|█████████ | 670/744 [50:13<00:07,  9.39it/s]

Ошибка получения температуры на точке: (np.float64(51.71915369108319), np.float64(103.42787191271782))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71915369108319&longitude=103.42787191271782&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E23ED0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71915369108319), np.float64(103.42787191271782))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71915369108319&longitude=103.42787191271782&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E22FD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71915369108319), np.float64(103.42787191271782))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71915369108319&longitude=103.42787191271782&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71915369108319), np.float64(103.42787191271782))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71915369108319&longitude=103.42787191271782&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7192950937897), np.float64(103.42802010476589))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7192950937897&longitude=103.42802010476589&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7192950937897), np.float64(103.42802010476589))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7192950937897&longitude=103.42802010476589&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3DD10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7192950937897), np.float64(103.42802010476589))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7192950937897&longitude=103.42802010476589&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3CE10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7192950937897), np.float64(103.42802010476589))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7192950937897&longitude=103.42802010476589&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3C2D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 90%|█████████ | 671/744 [50:13<00:07,  9.29it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.71943951398134), np.float64(103.42820073477924))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71943951398134&longitude=103.42820073477924&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E02850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71943951398134), np.float64(103.42820073477924))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71943951398134&longitude=103.42820073477924&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E22990>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71943951398134), np.float64(103.42820073477924))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71943951398134&longitude=103.42820073477924&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71943951398134), np.float64(103.42820073477924))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71943951398134&longitude=103.42820073477924&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71959139406681), np.float64(103.42842570506036))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71959139406681&longitude=103.42842570506036&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3E490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71959139406681), np.float64(103.42842570506036))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71959139406681&longitude=103.42842570506036&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3CF50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71959139406681), np.float64(103.42842570506036))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71959139406681&longitude=103.42842570506036&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3E0D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.71959139406681), np.float64(103.42842570506036))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.71959139406681&longitude=103.42842570506036&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 90%|█████████ | 672/744 [50:13<00:07,  9.19it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 90%|█████████ | 673/744 [50:14<00:07,  9.14it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.719706393778324), np.float64(103.42861287295818))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.719706393778324&longitude=103.42861287295818&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E22FD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.719706393778324), np.float64(103.42861287295818))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.719706393778324&longitude=103.42861287295818&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.719706393778324), np.float64(103.42861287295818))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.719706393778324&longitude=103.42861287295818&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21A90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.719706393778324), np.float64(103.42861287295818))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.719706393778324&longitude=103.42861287295818&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF4550>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72056470066309), np.float64(103.42966513708234))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72056470066309&longitude=103.42966513708234&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3EC10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72056470066309), np.float64(103.42966513708234))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72056470066309&longitude=103.42966513708234&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72056470066309), np.float64(103.42966513708234))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72056470066309&longitude=103.42966513708234&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3E850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72056470066309), np.float64(103.42966513708234))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72056470066309&longitude=103.42966513708234&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D1D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 91%|█████████ | 674/744 [50:14<00:07,  9.09it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 91%|█████████ | 675/744 [50:14<00:07,  9.01it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.720738876610994), np.float64(103.42980737797916))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.720738876610994&longitude=103.42980737797916&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.720738876610994), np.float64(103.42980737797916))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.720738876610994&longitude=103.42980737797916&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3E490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.720738876610994), np.float64(103.42980737797916))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.720738876610994&longitude=103.42980737797916&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3EFD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.720738876610994), np.float64(103.42980737797916))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.720738876610994&longitude=103.42980737797916&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D6D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.720916740596294), np.float64(103.42991843819618))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.720916740596294&longitude=103.42991843819618&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3FC50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.720916740596294), np.float64(103.42991843819618))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.720916740596294&longitude=103.42991843819618&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E22990>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.720916740596294), np.float64(103.42991843819618))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.720916740596294&longitude=103.42991843819618&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.720916740596294), np.float64(103.42991843819618))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.720916740596294&longitude=103.42991843819618&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E22FD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 91%|█████████ | 676/744 [50:14<00:07,  9.04it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 91%|█████████ | 677/744 [50:14<00:07,  9.09it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 91%|█████████ | 678/744 [50:14<00:07,  9.11it/s]

Ошибка получения температуры на точке: (np.float64(51.72109980136156), np.float64(103.42999999411404))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72109980136156&longitude=103.42999999411404&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E02490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72109980136156), np.float64(103.42999999411404))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72109980136156&longitude=103.42999999411404&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E22FD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72109980136156), np.float64(103.42999999411404))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72109980136156&longitude=103.42999999411404&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72109980136156), np.float64(103.42999999411404))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72109980136156&longitude=103.42999999411404&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21A90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72129753045738), np.float64(103.43006101436913))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72129753045738&longitude=103.43006101436913&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3E850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72129753045738), np.float64(103.43006101436913))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72129753045738&longitude=103.43006101436913&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D1D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72129753045738), np.float64(103.43006101436913))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72129753045738&longitude=103.43006101436913&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3E5D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72129753045738), np.float64(103.43006101436913))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72129753045738&longitude=103.43006101436913&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E50A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 91%|█████████▏| 679/744 [50:14<00:07,  9.20it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.72156969085336), np.float64(103.43023343011737))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72156969085336&longitude=103.43023343011737&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3ED50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72156969085336), np.float64(103.43023343011737))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72156969085336&longitude=103.43023343011737&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3CE10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72156969085336), np.float64(103.43023343011737))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72156969085336&longitude=103.43023343011737&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3F750>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72156969085336), np.float64(103.43023343011737))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72156969085336&longitude=103.43023343011737&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3E850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72166021540761), np.float64(103.4303339291364))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72166021540761&longitude=103.4303339291364&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20410>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72166021540761), np.float64(103.4303339291364))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72166021540761&longitude=103.4303339291364&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72166021540761), np.float64(103.4303339291364))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72166021540761&longitude=103.4303339291364&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E50410>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72166021540761), np.float64(103.4303339291364))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72166021540761&longitude=103.4303339291364&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E502D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 91%|█████████▏| 680/744 [50:14<00:06,  9.17it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 92%|█████████▏| 681/744 [50:14<00:06,  9.19it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.721786027774215), np.float64(103.4305009804666))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.721786027774215&longitude=103.4305009804666&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDE210>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.721786027774215), np.float64(103.4305009804666))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.721786027774215&longitude=103.4305009804666&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.721786027774215), np.float64(103.4305009804666))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.721786027774215&longitude=103.4305009804666&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20410>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.721786027774215), np.float64(103.4305009804666))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.721786027774215&longitude=103.4305009804666&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D1D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72190848737955), np.float64(103.4305807761848))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72190848737955&longitude=103.4305807761848&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3CA50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72190848737955), np.float64(103.4305807761848))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72190848737955&longitude=103.4305807761848&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3F390>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72190848737955), np.float64(103.4305807761848))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72190848737955&longitude=103.4305807761848&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72190848737955), np.float64(103.4305807761848))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72190848737955&longitude=103.4305807761848&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E50A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 92%|█████████▏| 682/744 [50:15<00:06,  9.16it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 92%|█████████▏| 683/744 [50:15<00:06,  9.17it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.722062630578876), np.float64(103.43057591468096))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.722062630578876&longitude=103.43057591468096&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.722062630578876), np.float64(103.43057591468096))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.722062630578876&longitude=103.43057591468096&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3FED0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.722062630578876), np.float64(103.43057591468096))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.722062630578876&longitude=103.43057591468096&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D6D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.722062630578876), np.float64(103.43057591468096))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.722062630578876&longitude=103.43057591468096&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3E490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72228768467903), np.float64(103.43057189136744))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72228768467903&longitude=103.43057189136744&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72228768467903), np.float64(103.43057189136744))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72228768467903&longitude=103.43057189136744&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72228768467903), np.float64(103.43057189136744))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72228768467903&longitude=103.43057189136744&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E50A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72228768467903), np.float64(103.43057189136744))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72228768467903&longitude=103.43057189136744&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 92%|█████████▏| 684/744 [50:15<00:06,  9.13it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 92%|█████████▏| 685/744 [50:15<00:06,  9.14it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.72243042849004), np.float64(103.43058572150767))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72243042849004&longitude=103.43058572150767&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72243042849004), np.float64(103.43058572150767))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72243042849004&longitude=103.43058572150767&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72243042849004), np.float64(103.43058572150767))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72243042849004&longitude=103.43058572150767&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D1D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72243042849004), np.float64(103.43058572150767))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72243042849004&longitude=103.43058572150767&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D6D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72256210818887), np.float64(103.43059116974473))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72256210818887&longitude=103.43059116974473&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E50690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72256210818887), np.float64(103.43059116974473))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72256210818887&longitude=103.43059116974473&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72256210818887), np.float64(103.43059116974473))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72256210818887&longitude=103.43059116974473&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E502D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72256210818887), np.float64(103.43059116974473))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72256210818887&longitude=103.43059116974473&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E520D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 92%|█████████▏| 686/744 [50:15<00:06,  9.09it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 92%|█████████▏| 687/744 [50:15<00:06,  9.11it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.722692027688026), np.float64(103.43058823607862))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.722692027688026&longitude=103.43058823607862&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3ED50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.722692027688026), np.float64(103.43058823607862))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.722692027688026&longitude=103.43058823607862&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3CA50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.722692027688026), np.float64(103.43058823607862))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.722692027688026&longitude=103.43058823607862&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D1D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.722692027688026), np.float64(103.43058823607862))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.722692027688026&longitude=103.43058823607862&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDE210>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.722810883075), np.float64(103.43057063408196))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.722810883075&longitude=103.43057063408196&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51A90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.722810883075), np.float64(103.43057063408196))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.722810883075&longitude=103.43057063408196&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.722810883075), np.float64(103.43057063408196))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.722810883075&longitude=103.43057063408196&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E50A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.722810883075), np.float64(103.43057063408196))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.722810883075&longitude=103.43057063408196&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 92%|█████████▏| 688/744 [50:15<00:06,  8.26it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 93%|█████████▎| 689/744 [50:15<00:06,  8.59it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 93%|█████████▎| 690/744 [50:15<00:06,  8.92it/s]

Ошибка получения температуры на точке: (np.float64(51.7236378416419), np.float64(103.43044909648597))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7236378416419&longitude=103.43044909648597&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDE210>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7236378416419), np.float64(103.43044909648597))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7236378416419&longitude=103.43044909648597&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E23ED0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7236378416419), np.float64(103.43044909648597))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7236378416419&longitude=103.43044909648597&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3E490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7236378416419), np.float64(103.43044909648597))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7236378416419&longitude=103.43044909648597&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D6D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72389139421284), np.float64(103.43044163659215))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72389139421284&longitude=103.43044163659215&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E52850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72389139421284), np.float64(103.43044163659215))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72389139421284&longitude=103.43044163659215&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E50690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72389139421284), np.float64(103.43044163659215))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72389139421284&longitude=103.43044163659215&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E52490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72389139421284), np.float64(103.43044163659215))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72389139421284&longitude=103.43044163659215&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E50E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 93%|█████████▎| 691/744 [50:16<00:05,  9.01it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.72406766563654), np.float64(103.43044146895409))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72406766563654&longitude=103.43044146895409&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72406766563654), np.float64(103.43044146895409))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72406766563654&longitude=103.43044146895409&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E50E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72406766563654), np.float64(103.43044146895409))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72406766563654&longitude=103.43044146895409&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E52490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72406766563654), np.float64(103.43044146895409))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72406766563654&longitude=103.43044146895409&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E50690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7241991776973), np.float64(103.43044876120985))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7241991776973&longitude=103.43044876120985&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E53B10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7241991776973), np.float64(103.43044876120985))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7241991776973&longitude=103.43044876120985&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D1D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7241991776973), np.float64(103.43044876120985))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7241991776973&longitude=103.43044876120985&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7241991776973), np.float64(103.43044876120985))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7241991776973&longitude=103.43044876120985&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 93%|█████████▎| 692/744 [50:16<00:05,  9.05it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 93%|█████████▎| 693/744 [50:16<00:05,  9.07it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.72478565946221), np.float64(103.4306915011257))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72478565946221&longitude=103.4306915011257&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72478565946221), np.float64(103.4306915011257))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72478565946221&longitude=103.4306915011257&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3D6D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72478565946221), np.float64(103.4306915011257))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72478565946221&longitude=103.4306915011257&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3EFD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72478565946221), np.float64(103.4306915011257))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72478565946221&longitude=103.4306915011257&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E52850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.725024627521634), np.float64(103.43116130679846))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725024627521634&longitude=103.43116130679846&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DDE210>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.725024627521634), np.float64(103.43116130679846))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725024627521634&longitude=103.43116130679846&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E52990>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.725024627521634), np.float64(103.43116130679846))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725024627521634&longitude=103.43116130679846&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E50410>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.725024627521634), np.float64(103.43116130679846))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725024627521634&longitude=103.43116130679846&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E70690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 93%|█████████▎| 694/744 [50:16<00:05,  9.05it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 93%|█████████▎| 695/744 [50:16<00:05,  9.13it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.725050108507276), np.float64(103.43140941113234))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725050108507276&longitude=103.43140941113234&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E53890>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.725050108507276), np.float64(103.43140941113234))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725050108507276&longitude=103.43140941113234&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.725050108507276), np.float64(103.43140941113234))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725050108507276&longitude=103.43140941113234&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E52210>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.725050108507276), np.float64(103.43140941113234))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725050108507276&longitude=103.43140941113234&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.725073494017124), np.float64(103.43168970197439))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725073494017124&longitude=103.43168970197439&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3FB10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.725073494017124), np.float64(103.43168970197439))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725073494017124&longitude=103.43168970197439&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.725073494017124), np.float64(103.43168970197439))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725073494017124&longitude=103.43168970197439&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.725073494017124), np.float64(103.43168970197439))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725073494017124&longitude=103.43168970197439&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E707D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 94%|█████████▎| 696/744 [50:16<00:05,  9.08it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 94%|█████████▎| 697/744 [50:16<00:05,  9.15it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.72511791810393), np.float64(103.4319590125233))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72511791810393&longitude=103.4319590125233&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72511791810393), np.float64(103.4319590125233))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72511791810393&longitude=103.4319590125233&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3DD10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72511791810393), np.float64(103.4319590125233))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72511791810393&longitude=103.4319590125233&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3FB10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72511791810393), np.float64(103.4319590125233))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72511791810393&longitude=103.4319590125233&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.725207436829805), np.float64(103.43215598724782))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725207436829805&longitude=103.43215598724782&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.725207436829805), np.float64(103.43215598724782))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725207436829805&longitude=103.43215598724782&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E53890>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.725207436829805), np.float64(103.43215598724782))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725207436829805&longitude=103.43215598724782&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E711D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.725207436829805), np.float64(103.43215598724782))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725207436829805&longitude=103.43215598724782&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E707D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 94%|█████████▍| 698/744 [50:16<00:05,  9.13it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 94%|█████████▍| 699/744 [50:16<00:04,  9.11it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.72545202076435), np.float64(103.4321918617934))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72545202076435&longitude=103.4321918617934&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51A90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72545202076435), np.float64(103.4321918617934))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72545202076435&longitude=103.4321918617934&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E50690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72545202076435), np.float64(103.4321918617934))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72545202076435&longitude=103.4321918617934&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72545202076435), np.float64(103.4321918617934))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72545202076435&longitude=103.4321918617934&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72566148452461), np.float64(103.43218859285116))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72566148452461&longitude=103.43218859285116&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72566148452461), np.float64(103.43218859285116))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72566148452461&longitude=103.43218859285116&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E71D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72566148452461), np.float64(103.43218859285116))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72566148452461&longitude=103.43218859285116&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E70A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72566148452461), np.float64(103.43218859285116))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72566148452461&longitude=103.43218859285116&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E71590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 94%|█████████▍| 700/744 [50:17<00:04,  9.04it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 94%|█████████▍| 701/744 [50:17<00:04,  9.10it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.725888634100556), np.float64(103.43220049515367))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725888634100556&longitude=103.43220049515367&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E3FB10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.725888634100556), np.float64(103.43220049515367))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725888634100556&longitude=103.43220049515367&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.725888634100556), np.float64(103.43220049515367))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725888634100556&longitude=103.43220049515367&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E53750>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.725888634100556), np.float64(103.43220049515367))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.725888634100556&longitude=103.43220049515367&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E52FD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.726060127839446), np.float64(103.4321762714535))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.726060127839446&longitude=103.4321762714535&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E70F50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.726060127839446), np.float64(103.4321762714535))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.726060127839446&longitude=103.4321762714535&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E70690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.726060127839446), np.float64(103.4321762714535))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.726060127839446&longitude=103.4321762714535&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E716D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.726060127839446), np.float64(103.4321762714535))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.726060127839446&longitude=103.4321762714535&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E70050>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 94%|█████████▍| 702/744 [50:17<00:04,  9.06it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 94%|█████████▍| 703/744 [50:17<00:04,  8.98it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.726245703175664), np.float64(103.43214383348823))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.726245703175664&longitude=103.43214383348823&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E50690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.726245703175664), np.float64(103.43214383348823))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.726245703175664&longitude=103.43214383348823&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E52C10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.726245703175664), np.float64(103.43214383348823))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.726245703175664&longitude=103.43214383348823&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E52850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.726245703175664), np.float64(103.43214383348823))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.726245703175664&longitude=103.43214383348823&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.726384591311216), np.float64(103.43241322785616))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.726384591311216&longitude=103.43241322785616&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E71950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.726384591311216), np.float64(103.43241322785616))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.726384591311216&longitude=103.43241322785616&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E71D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.726384591311216), np.float64(103.43241322785616))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.726384591311216&longitude=103.43241322785616&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E70E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.726384591311216), np.float64(103.43241322785616))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.726384591311216&longitude=103.43241322785616&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E702D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 95%|█████████▍| 704/744 [50:17<00:04,  8.98it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 95%|█████████▍| 705/744 [50:17<00:04,  8.96it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.72661601565778), np.float64(103.4325996413827))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72661601565778&longitude=103.4325996413827&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E21310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72661601565778), np.float64(103.4325996413827))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72661601565778&longitude=103.4325996413827&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72661601565778), np.float64(103.4325996413827))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72661601565778&longitude=103.4325996413827&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E53750>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72661601565778), np.float64(103.4325996413827))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72661601565778&longitude=103.4325996413827&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E53890>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72673168592155), np.float64(103.43262730166316))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72673168592155&longitude=103.43262730166316&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E72490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72673168592155), np.float64(103.43262730166316))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72673168592155&longitude=103.43262730166316&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E70F50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72673168592155), np.float64(103.43262730166316))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72673168592155&longitude=103.43262730166316&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E720D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72673168592155), np.float64(103.43262730166316))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72673168592155&longitude=103.43262730166316&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E71590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 95%|█████████▍| 706/744 [50:17<00:04,  8.90it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 95%|█████████▌| 707/744 [50:17<00:04,  8.99it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.72906336374581), np.float64(103.43236251734197))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72906336374581&longitude=103.43236251734197&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51A90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72906336374581), np.float64(103.43236251734197))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72906336374581&longitude=103.43236251734197&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72906336374581), np.float64(103.43236251734197))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72906336374581&longitude=103.43236251734197&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72906336374581), np.float64(103.43236251734197))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72906336374581&longitude=103.43236251734197&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.729272827506065), np.float64(103.43238129280508))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.729272827506065&longitude=103.43238129280508&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E72C10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.729272827506065), np.float64(103.43238129280508))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.729272827506065&longitude=103.43238129280508&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E71950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.729272827506065), np.float64(103.43238129280508))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.729272827506065&longitude=103.43238129280508&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E72850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.729272827506065), np.float64(103.43238129280508))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.729272827506065&longitude=103.43238129280508&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E711D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 95%|█████████▌| 708/744 [50:17<00:03,  9.02it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 95%|█████████▌| 709/744 [50:18<00:03,  9.07it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.72960869036615), np.float64(103.43241607770324))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72960869036615&longitude=103.43241607770324&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E71590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72960869036615), np.float64(103.43241607770324))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72960869036615&longitude=103.43241607770324&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E711D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72960869036615), np.float64(103.43241607770324))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72960869036615&longitude=103.43241607770324&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E72850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72960869036615), np.float64(103.43241607770324))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72960869036615&longitude=103.43241607770324&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E71950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72985746525228), np.float64(103.4324701409787))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72985746525228&longitude=103.4324701409787&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E73C50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72985746525228), np.float64(103.4324701409787))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72985746525228&longitude=103.4324701409787&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72985746525228), np.float64(103.4324701409787))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72985746525228&longitude=103.4324701409787&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.72985746525228), np.float64(103.4324701409787))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.72985746525228&longitude=103.4324701409787&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51A90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 95%|█████████▌| 710/744 [50:18<00:03,  9.08it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 96%|█████████▌| 711/744 [50:18<00:03,  9.11it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.730139097198844), np.float64(103.43237617984414))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.730139097198844&longitude=103.43237617984414&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E23ED0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.730139097198844), np.float64(103.43237617984414))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.730139097198844&longitude=103.43237617984414&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E53890>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.730139097198844), np.float64(103.43237617984414))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.730139097198844&longitude=103.43237617984414&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.730139097198844), np.float64(103.43237617984414))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.730139097198844&longitude=103.43237617984414&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.730271615087986), np.float64(103.43236276879907))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.730271615087986&longitude=103.43236276879907&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E720D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.730271615087986), np.float64(103.43236276879907))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.730271615087986&longitude=103.43236276879907&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E70F50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.730271615087986), np.float64(103.43236276879907))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.730271615087986&longitude=103.43236276879907&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E725D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.730271615087986), np.float64(103.43236276879907))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.730271615087986&longitude=103.43236276879907&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 96%|█████████▌| 712/744 [50:18<00:03,  9.09it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 96%|█████████▌| 713/744 [50:18<00:03,  9.13it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.73045978881419), np.float64(103.43237768858671))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73045978881419&longitude=103.43237768858671&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E73C50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73045978881419), np.float64(103.43237768858671))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73045978881419&longitude=103.43237768858671&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E71D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73045978881419), np.float64(103.43237768858671))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73045978881419&longitude=103.43237768858671&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E71590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73045978881419), np.float64(103.43237768858671))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73045978881419&longitude=103.43237768858671&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E711D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.730599934235215), np.float64(103.43240291811526))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.730599934235215&longitude=103.43240291811526&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E52850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.730599934235215), np.float64(103.43240291811526))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.730599934235215&longitude=103.43240291811526&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E52C10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.730599934235215), np.float64(103.43240291811526))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.730599934235215&longitude=103.43240291811526&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84410>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.730599934235215), np.float64(103.43240291811526))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.730599934235215&longitude=103.43240291811526&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E842D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 96%|█████████▌| 714/744 [50:18<00:03,  9.16it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 96%|█████████▌| 715/744 [50:18<00:03,  9.18it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))

Ошибка получения температуры на точке: (np.float64(51.73076522536576), np.float64(103.43237458728254))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73076522536576&longitude=103.43237458728254&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73076522536576), np.float64(103.43237458728254))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73076522536576&longitude=103.43237458728254&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73076522536576), np.float64(103.43237458728254))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73076522536576&longitude=103.43237458728254&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E52850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73076522536576), np.float64(103.43237458728254))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73076522536576&longitude=103.43237458728254&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E72D50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73098851926625), np.float64(103.43227551318705))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73098851926625&longitude=103.43227551318705&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E72490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73098851926625), np.float64(103.43227551318705))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73098851926625&longitude=103.43227551318705&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E73ED0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73098851926625), np.float64(103.43227551318705))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73098851926625&longitude=103.43227551318705&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E85310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73098851926625), np.float64(103.43227551318705))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73098851926625&longitude=103.43227551318705&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 96%|█████████▌| 716/744 [50:18<00:03,  9.20it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 96%|█████████▋| 717/744 [50:18<00:02,  9.21it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))

Ошибка получения температуры на точке: (np.float64(51.73109086230397), np.float64(103.43224450014532))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73109086230397&longitude=103.43224450014532&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E725D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73109086230397), np.float64(103.43224450014532))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73109086230397&longitude=103.43224450014532&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E73B10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73109086230397), np.float64(103.43224450014532))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73109086230397&longitude=103.43224450014532&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E71950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73109086230397), np.float64(103.43224450014532))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73109086230397&longitude=103.43224450014532&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E70F50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.731807263568044), np.float64(103.43212673440576))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.731807263568044&longitude=103.43212673440576&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.731807263568044), np.float64(103.43212673440576))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.731807263568044&longitude=103.43212673440576&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E85D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.731807263568044), np.float64(103.43212673440576))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.731807263568044&longitude=103.43212673440576&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.731807263568044), np.float64(103.43212673440576))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.731807263568044&longitude=103.43212673440576&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E85310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 97%|█████████▋| 718/744 [50:19<00:02,  9.19it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 97%|█████████▋| 719/744 [50:19<00:02,  9.08it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.73205687664449), np.float64(103.43235187232494))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73205687664449&longitude=103.43235187232494&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73205687664449), np.float64(103.43235187232494))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73205687664449&longitude=103.43235187232494&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73205687664449), np.float64(103.43235187232494))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73205687664449&longitude=103.43235187232494&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E72D50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73205687664449), np.float64(103.43235187232494))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73205687664449&longitude=103.43235187232494&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E71950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73244177363813), np.float64(103.4324231185019))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73244177363813&longitude=103.4324231185019&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73244177363813), np.float64(103.4324231185019))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73244177363813&longitude=103.4324231185019&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E85590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73244177363813), np.float64(103.4324231185019))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73244177363813&longitude=103.4324231185019&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E842D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73244177363813), np.float64(103.4324231185019))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73244177363813&longitude=103.4324231185019&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E860D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 97%|█████████▋| 720/744 [50:19<00:02,  9.04it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 97%|█████████▋| 721/744 [50:19<00:02,  9.21it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))

Ошибка получения температуры на точке: (np.float64(51.732644364237785), np.float64(103.43238313682377))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.732644364237785&longitude=103.43238313682377&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E725D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.732644364237785), np.float64(103.43238313682377))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.732644364237785&longitude=103.43238313682377&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E73ED0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.732644364237785), np.float64(103.43238313682377))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.732644364237785&longitude=103.43238313682377&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E72C10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.732644364237785), np.float64(103.43238313682377))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.732644364237785&longitude=103.43238313682377&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51A90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73274620436132), np.float64(103.43226746656))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73274620436132&longitude=103.43226746656&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E85A90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73274620436132), np.float64(103.43226746656))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73274620436132&longitude=103.43226746656&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E85D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73274620436132), np.float64(103.43226746656))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73274620436132&longitude=103.43226746656&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73274620436132), np.float64(103.43226746656))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73274620436132&longitude=103.43226746656&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E85310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73289037309587), np.float64(103.43224542215466))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73289037309587&longitude=103.43224542215466&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73289037309587), np.float64(103.43224542215466))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73289037309587&longitude=103.43224542215466&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E20E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 97%|█████████▋| 723/744 [50:19<00:02,  9.36it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 97%|█████████▋| 724/744 [50:19<00:02,  9.28it/s]

Ошибка получения температуры на точке: (np.float64(51.73289037309587), np.float64(103.43224542215466))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73289037309587&longitude=103.43224542215466&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E72C10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73289037309587), np.float64(103.43224542215466))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73289037309587&longitude=103.43224542215466&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E73ED0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.733071925118566), np.float64(103.43228783458471))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.733071925118566&longitude=103.43228783458471&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E86850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.733071925118566), np.float64(103.43228783458471))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.733071925118566&longitude=103.43228783458471&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.733071925118566), np.float64(103.43228783458471))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.733071925118566&longitude=103.43228783458471&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E86490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.733071925118566), np.float64(103.43228783458471))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.733071925118566&longitude=103.43228783458471&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 97%|█████████▋| 725/744 [50:19<00:02,  9.19it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.73332673497498), np.float64(103.43235162086785))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73332673497498&longitude=103.43235162086785&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E85310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73332673497498), np.float64(103.43235162086785))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73332673497498&longitude=103.43235162086785&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73332673497498), np.float64(103.43235162086785))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73332673497498&longitude=103.43235162086785&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E86490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73332673497498), np.float64(103.43235162086785))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73332673497498&longitude=103.43235162086785&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.733570815995336), np.float64(103.43243326060474))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.733570815995336&longitude=103.43243326060474&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E87B10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.733570815995336), np.float64(103.43243326060474))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.733570815995336&longitude=103.43243326060474&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E71950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.733570815995336), np.float64(103.43243326060474))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.733570815995336&longitude=103.43243326060474&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E70F50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.733570815995336), np.float64(103.43243326060474))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.733570815995336&longitude=103.43243326060474&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E52FD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 98%|█████████▊| 726/744 [50:19<00:01,  9.01it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 98%|█████████▊| 727/744 [50:20<00:01,  9.00it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.73385303467512), np.float64(103.43248640187085))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73385303467512&longitude=103.43248640187085&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51A90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73385303467512), np.float64(103.43248640187085))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73385303467512&longitude=103.43248640187085&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E71D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73385303467512), np.float64(103.43248640187085))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73385303467512&longitude=103.43248640187085&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E72D50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73385303467512), np.float64(103.43248640187085))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73385303467512&longitude=103.43248640187085&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E86850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.734015895053744), np.float64(103.43255530111492))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.734015895053744&longitude=103.43255530111492&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.734015895053744), np.float64(103.43255530111492))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.734015895053744&longitude=103.43255530111492&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E86990>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.734015895053744), np.float64(103.43255530111492))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.734015895053744&longitude=103.43255530111492&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84410>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.734015895053744), np.float64(103.43255530111492))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.734015895053744&longitude=103.43255530111492&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9C690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 98%|█████████▊| 728/744 [50:20<00:01,  8.91it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 98%|█████████▊| 729/744 [50:20<00:01,  8.94it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.734241703525186), np.float64(103.43239101581275))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.734241703525186&longitude=103.43239101581275&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E87890>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.734241703525186), np.float64(103.43239101581275))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.734241703525186&longitude=103.43239101581275&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.734241703525186), np.float64(103.43239101581275))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.734241703525186&longitude=103.43239101581275&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E86490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.734241703525186), np.float64(103.43239101581275))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.734241703525186&longitude=103.43239101581275&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84A50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73446617089212), np.float64(103.43186027370393))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73446617089212&longitude=103.43186027370393&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E72490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73446617089212), np.float64(103.43186027370393))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73446617089212&longitude=103.43186027370393&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73446617089212), np.float64(103.43186027370393))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73446617089212&longitude=103.43186027370393&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E552DF5950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73446617089212), np.float64(103.43186027370393))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73446617089212&longitude=103.43186027370393&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9C7D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 98%|█████████▊| 730/744 [50:20<00:01,  8.87it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 98%|█████████▊| 731/744 [50:20<00:01,  8.89it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.7345726210624), np.float64(103.43110581859946))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7345726210624&longitude=103.43110581859946&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E71950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7345726210624), np.float64(103.43110581859946))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7345726210624&longitude=103.43110581859946&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51A90>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7345726210624), np.float64(103.43110581859946))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7345726210624&longitude=103.43110581859946&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E52FD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7345726210624), np.float64(103.43110581859946))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7345726210624&longitude=103.43110581859946&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E85590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.734738582745194), np.float64(103.43050357885659))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.734738582745194&longitude=103.43050357885659&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.734738582745194), np.float64(103.43050357885659))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.734738582745194&longitude=103.43050357885659&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E87890>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.734738582745194), np.float64(103.43050357885659))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.734738582745194&longitude=103.43050357885659&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9D1D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.734738582745194), np.float64(103.43050357885659))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.734738582745194&longitude=103.43050357885659&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9C7D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 98%|█████████▊| 732/744 [50:20<00:01,  8.81it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 99%|█████████▊| 733/744 [50:20<00:01,  8.88it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

Ошибка получения температуры на точке: (np.float64(51.73502029851079), np.float64(103.4299208689481))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73502029851079&longitude=103.4299208689481&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84410>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73502029851079), np.float64(103.4299208689481))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73502029851079&longitude=103.4299208689481&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73502029851079), np.float64(103.4299208689481))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73502029851079&longitude=103.4299208689481&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73502029851079), np.float64(103.4299208689481))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73502029851079&longitude=103.4299208689481&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E85590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73540812917054), np.float64(103.42940135858953))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73540812917054&longitude=103.42940135858953&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E70F50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73540812917054), np.float64(103.42940135858953))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73540812917054&longitude=103.42940135858953&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9DD10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73540812917054), np.float64(103.42940135858953))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73540812917054&longitude=103.42940135858953&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9CA50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73540812917054), np.float64(103.42940135858953))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73540812917054&longitude=103.42940135858953&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9D590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 99%|█████████▊| 734/744 [50:20<00:01,  9.00it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 99%|█████████▉| 735/744 [50:20<00:00,  9.11it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.735869301483035), np.float64(103.42906733974814))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.735869301483035&longitude=103.42906733974814&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.735869301483035), np.float64(103.42906733974814))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.735869301483035&longitude=103.42906733974814&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E71D10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.735869301483035), np.float64(103.42906733974814))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.735869301483035&longitude=103.42906733974814&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E85310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.735869301483035), np.float64(103.42906733974814))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.735869301483035&longitude=103.42906733974814&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E86FD0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73636048100889), np.float64(103.42877531424165))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73636048100889&longitude=103.42877531424165&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9CF50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73636048100889), np.float64(103.42877531424165))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73636048100889&longitude=103.42877531424165&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9C690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73636048100889), np.float64(103.42877531424165))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73636048100889&longitude=103.42877531424165&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9D6D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73636048100889), np.float64(103.42877531424165))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73636048100889&longitude=103.42877531424165&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9C050>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 99%|█████████▉| 736/744 [50:21<00:00,  9.12it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 99%|█████████▉| 737/744 [50:21<00:00,  9.19it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'

Ошибка получения температуры на точке: (np.float64(51.73671788536012), np.float64(103.42853081412613))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73671788536012&longitude=103.42853081412613&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84690>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73671788536012), np.float64(103.42853081412613))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73671788536012&longitude=103.42853081412613&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E86990>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73671788536012), np.float64(103.42853081412613))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73671788536012&longitude=103.42853081412613&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E87750>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73671788536012), np.float64(103.42853081412613))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73671788536012&longitude=103.42853081412613&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E51590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73700027167797), np.float64(103.42829687520862))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73700027167797&longitude=103.42829687520862&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9D950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73700027167797), np.float64(103.42829687520862))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73700027167797&longitude=103.42829687520862&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9DD10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73700027167797), np.float64(103.42829687520862))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73700027167797&longitude=103.42829687520862&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9CE10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73700027167797), np.float64(103.42829687520862))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73700027167797&longitude=103.42829687520862&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9C2D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 99%|█████████▉| 738/744 [50:21<00:00,  9.18it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 99%|█████████▉| 739/744 [50:21<00:00,  9.27it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.7372939735651), np.float64(103.42815748415887))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7372939735651&longitude=103.42815748415887&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E73ED0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7372939735651), np.float64(103.42815748415887))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7372939735651&longitude=103.42815748415887&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E85590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7372939735651), np.float64(103.42815748415887))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7372939735651&longitude=103.42815748415887&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E85310>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.7372939735651), np.float64(103.42815748415887))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.7372939735651&longitude=103.42815748415887&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E87890>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73758180812001), np.float64(103.4281062707305))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73758180812001&longitude=103.4281062707305&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9E490>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73758180812001), np.float64(103.4281062707305))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73758180812001&longitude=103.4281062707305&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9CF50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73758180812001), np.float64(103.4281062707305))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73758180812001&longitude=103.4281062707305&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9E0D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73758180812001), np.float64(103.4281062707305))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73758180812001&longitude=103.4281062707305&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9D590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
 99%|█████████▉| 740/744 [50:21<00:00,  9.30it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
100%|█████████▉| 741/744 [50:21<00:00,  9.41it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.73781071789563), np.float64(103.42785950750113))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73781071789563&longitude=103.42785950750113&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84410>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73781071789563), np.float64(103.42785950750113))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73781071789563&longitude=103.42785950750113&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73781071789563), np.float64(103.42785950750113))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73781071789563&longitude=103.42785950750113&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E85590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73781071789563), np.float64(103.42785950750113))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73781071789563&longitude=103.42785950750113&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E73ED0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73801716417074), np.float64(103.42755507677794))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73801716417074&longitude=103.42755507677794&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9EC10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73801716417074), np.float64(103.42755507677794))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73801716417074&longitude=103.42755507677794&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9D950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73801716417074), np.float64(103.42755507677794))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73801716417074&longitude=103.42755507677794&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9E850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73801716417074), np.float64(103.42755507677794))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73801716417074&longitude=103.42755507677794&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9D1D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
100%|█████████▉| 742/744 [50:21<00:00,  9.30it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
100%|█████████▉| 743/744 [50:21<00:00,  9.29it/s]C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\statespace\sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Ошибка получения температуры на точке: (np.float64(51.738099893555045), np.float64(103.42745633795857))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.738099893555045&longitude=103.42745633795857&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9D590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.738099893555045), np.float64(103.42745633795857))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.738099893555045&longitude=103.42745633795857&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9D1D0>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.738099893555045), np.float64(103.42745633795857))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.738099893555045&longitude=103.42745633795857&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9E850>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.738099893555045), np.float64(103.42745633795857))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.738099893555045&longitude=103.42745633795857&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9D950>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73825311474502), np.float64(103.42725877650082))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73825311474502&longitude=103.42725877650082&start_date=2021-07-16&end_date=2021-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E9FC50>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73825311474502), np.float64(103.42725877650082))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73825311474502&longitude=103.42725877650082&start_date=2020-07-16&end_date=2020-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E85590>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73825311474502), np.float64(103.42725877650082))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73825311474502&longitude=103.42725877650082&start_date=2019-07-16&end_date=2019-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84E10>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))
Ошибка получения температуры на точке: (np.float64(51.73825311474502), np.float64(103.42725877650082))
failed to request 'https://archive-api.open-meteo.com/v1/archive': HTTPSConnectionPool(host='archive-api.open-meteo.com', port=443): Max retries exceeded with url: /v1/archive?latitude=51.73825311474502&longitude=103.42725877650082&start_date=2018-07-16&end_date=2018-07-16&hourly=temperature_2m&format=flatbuffers (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E553E84410>: Failed to resolve 'archive-api.open-meteo.com' (Name or service not known: archive-api.open-meteo.com using 1 resolver(s))"))

C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
C:\Users\demoexam\AppData\Roaming\Python\Python313\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
C:\Users\demoexam\AppData\Local\Temp\ipykernel_6252\4283830431.py:141: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predictions.append(int(predict))
100%|██████████| 744/744 [50:21<00:00,  4.06s/it]

NameError: name 'points_predictions_flood' is not defined

In [33]:
a = agent.points_predictions_flood

In [36]:
pd.Series(a).T

point_0      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
point_1      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
point_2      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
point_3      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
point_4      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
                          ...
point_739    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
point_740    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
point_741    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
point_742    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
point_743    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Length: 744, dtype: object