In [1]:
import pandas as pd
import sqlite3
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score, recall_score
from joblib import dump, load
import openmeteo_requests

import numpy as np

In [2]:
try:
    con = sqlite3.connect(r"C:\Users\demoexam\Desktop\Гурбанов\MachineLearning\Проект №6 (последний срез)\clear_data.db")
    data = pd.read_sql("SELECT * FROM Clear_data", con=con)
except Exception as e:
    print(f"Ошибка в загрузке из базы данных: {e}")

In [3]:
data = data.drop(["level_0", "index"], axis=1)

In [4]:
data = data.drop(["country", "cluster_2", "track_id", "point_id"], axis=1)

In [5]:
data

,time,latitude,longitude,elevation,steps,temperature,water_feature,forest_feature,buildings_feature,place_type,cluster,fire,flood,evacuation,dangerous
0,2012-09-12 21:13:13+00:00,51.505713,104.139225,501.46,3.0,-25.937000,1,3,94,2,2,1,0,0,2
1,2012-09-12 21:13:19+00:00,51.505694,104.139221,505.79,0.0,-25.937000,1,3,94,2,2,1,0,0,2
2,2012-09-12 21:13:20+00:00,51.505693,104.139224,505.79,5.0,-25.937000,1,3,94,2,2,1,0,0,2
3,2012-09-12 21:13:30+00:00,51.505724,104.139204,511.56,1.0,-25.937000,1,3,94,2,2,1,0,0,2
4,2012-09-12 21:13:37+00:00,51.505717,104.139202,514.92,1.0,-25.937000,1,3,94,2,2,1,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2741,2022-07-16 09:35:57+00:00,51.737582,103.428106,669.33,44.0,-29.246500,0,0,0,0,1,0,0,1,1
2742,2022-07-16 09:36:02+00:00,51.737811,103.427860,668.52,44.0,-29.246500,0,0,0,0,1,0,0,1,1
2743,2022-07-16 09:36:07+00:00,51.738017,103.427555,668.27,16.0,-29.246500,0,0,0,0,1,0,0,1,1
2744,2022-07-16 09:36:24+00:00,51.738100,103.427456,668.27,31.0,-29.207499,0,0,0,0,1,0,0,1,1
2745,2022-07-16 09:36:30+00:00,51.738253,103.427259,668.03,0.0,-29.207499,0,0,0,0,1,0,0,1,1

In [6]:
data["time"] = pd.to_datetime(data["time"])

In [7]:
data['date_day'] = data['time'].dt.day
data['date_month'] = data['time'].dt.month
data['date_year'] = data['time'].dt.year
data['date_hour'] = data['time'].dt.hour

In [8]:
data = data.drop("time", axis=1)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(data.drop("dangerous", axis=1), data["dangerous"], test_size=0.33, random_state=42)

In [10]:
LR = LogisticRegression(max_iter=5000)

In [11]:
LR.fit(X_train, y_train)

LogisticRegression(max_iter=5000)

In [12]:
GBC = GradientBoostingClassifier()

In [13]:
GBC.fit(X_train, y_train)

GradientBoostingClassifier()

In [14]:
MLPC = MLPClassifier()

In [15]:
MLPC.fit(X_train, y_train)

MLPClassifier()

In [17]:
models = {"MLPClassifier": MLPC, "GradientBoostingClassifier": GBC, "LogisticRegression": LR}

In [18]:
for name_model in models:
    model = models[name_model]
    model_pred = model.predict(X_test)
    model_proba = model.predict_proba(X_test)
    print(f"Модель {name_model}:\n\nТочность: {accuracy_score(y_test, model_pred)}\nПолнота: {recall_score(y_test, model_pred, average="micro")}\nF1-метрика: {f1_score(y_test, model_pred, average="micro")}\nROC-AUC метрика: {roc_auc_score(y_test, model_proba, average="micro", multi_class="ovr")}\n\n")

Модель MLPClassifier:

Точность: 0.9944873208379272
Полнота: 0.9944873208379272
F1-метрика: 0.9944873208379272
ROC-AUC метрика: 0.9998213089665215


Модель GradientBoostingClassifier:

Точность: 1.0
Полнота: 1.0
F1-метрика: 1.0
ROC-AUC метрика: 1.0


Модель LogisticRegression:

Точность: 1.0
Полнота: 1.0
F1-метрика: 1.0
ROC-AUC метрика: 1.0

### Лучше всего будет выбрать алгоритм Логистической Регресии, так как она использует линейные зависимости, которые присуствуют в датасете. Помимо этого это достаточно простой алгоритм и он полностью справляется со своей задачей, брать более сложные алгоритмы смысла не имеет.

In [19]:
dump(models["LogisticRegression"], 'best_model.joblib')

['best_model.joblib']

In [20]:
data

,latitude,longitude,elevation,steps,temperature,water_feature,forest_feature,buildings_feature,place_type,cluster,fire,flood,evacuation,dangerous,date_day,date_month,date_year,date_hour
0,51.505713,104.139225,501.46,3.0,-25.937000,1,3,94,2,2,1,0,0,2,12,9,2012,21
1,51.505694,104.139221,505.79,0.0,-25.937000,1,3,94,2,2,1,0,0,2,12,9,2012,21
2,51.505693,104.139224,505.79,5.0,-25.937000,1,3,94,2,2,1,0,0,2,12,9,2012,21
3,51.505724,104.139204,511.56,1.0,-25.937000,1,3,94,2,2,1,0,0,2,12,9,2012,21
4,51.505717,104.139202,514.92,1.0,-25.937000,1,3,94,2,2,1,0,0,2,12,9,2012,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2741,51.737582,103.428106,669.33,44.0,-29.246500,0,0,0,0,1,0,0,1,1,16,7,2022,9
2742,51.737811,103.427860,668.52,44.0,-29.246500,0,0,0,0,1,0,0,1,1,16,7,2022,9
2743,51.738017,103.427555,668.27,16.0,-29.246500,0,0,0,0,1,0,0,1,1,16,7,2022,9
2744,51.738100,103.427456,668.27,31.0,-29.207499,0,0,0,0,1,0,0,1,1,16,7,2022,9
2745,51.738253,103.427259,668.03,0.0,-29.207499,0,0,0,0,1,0,0,1,1,16,7,2022,9

In [21]:
def __temperature_forecast(row):
    params = {
    "latitude": row["latitude"],
    "longitude": row["longitude"],
    "start_date": str(pd.to_datetime(f"{int(row["date_year"])}-{int(row["date_month"])}-{int(row["date_day"])}").strftime("%Y-%m-%d")),
    "end_date": str(pd.to_datetime(f"{int(row["date_year"])}-{int(row["date_month"])}-{int(row["date_day"])}").strftime("%Y-%m-%d")),
    "hourly": ["temperature_2m"]
    }
    try:
        openmeteo = openmeteo_requests.Client()
        responses = openmeteo.weather_api("https://archive-api.open-meteo.com/v1/archive", params=params)
        response = responses[0]
        current = response.Hourly()
        temperatures = current.Variables(0).ValuesAsNumpy()
        return temperatures.mean()
    except Exception as e:
        print(f"Ошибка получения температуры на точке: {(row["latitude"], row["longitude"])}\n{e}")
        return None

In [ ]:
points_predictions = {}
prediction_data = data
for i in range(len(data.index.tolist())):
    row = data.iloc[i]
    for k in range(10):
        row["date_year"] = row["date_year"] - 1
        row["temperature"] = __temperature_forecast(row)
        model = load(r"C:\Users\demoexam\Desktop\Гурбанов\MachineLearning\Проект №6 (последний срез)\best_model.joblib")
        predict = model.predict(pd.DataFrame(row).T.drop("dangerous", axis=1))

C:\Users\demoexam\AppData\Local\Temp\ipykernel_4868\2178482200.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row["date_year"] = row["date_year"]-1

ERROR! Session/line number was not unique in database. History logging moved to new session 195

C:\Users\demoexam\AppData\Local\Temp\ipykernel_4868\2178482200.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row["temperature"] = __temperature_forecast(row)
C:\Users\demoexam\AppData\Local\Temp\ipykernel_4868\2178482200.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row["date_year"] = row["date_year"]-1

[2]

C:\Users\demoexam\AppData\Local\Temp\ipykernel_4868\2178482200.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row["temperature"] = __temperature_forecast(row)
C:\Users\demoexam\AppData\Local\Temp\ipykernel_4868\2178482200.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row["date_year"] = row["date_year"]-1

[2]

C:\Users\demoexam\AppData\Local\Temp\ipykernel_4868\2178482200.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row["temperature"] = __temperature_forecast(row)
C:\Users\demoexam\AppData\Local\Temp\ipykernel_4868\2178482200.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row["date_year"] = row["date_year"]-1

[2]

C:\Users\demoexam\AppData\Local\Temp\ipykernel_4868\2178482200.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row["temperature"] = __temperature_forecast(row)
C:\Users\demoexam\AppData\Local\Temp\ipykernel_4868\2178482200.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row["date_year"] = row["date_year"]-1

[2]

C:\Users\demoexam\AppData\Local\Temp\ipykernel_4868\2178482200.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row["temperature"] = __temperature_forecast(row)
C:\Users\demoexam\AppData\Local\Temp\ipykernel_4868\2178482200.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row["date_year"] = row["date_year"]-1

[2]

C:\Users\demoexam\AppData\Local\Temp\ipykernel_4868\2178482200.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row["temperature"] = __temperature_forecast(row)
C:\Users\demoexam\AppData\Local\Temp\ipykernel_4868\2178482200.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row["date_year"] = row["date_year"]-1

[2]

C:\Users\demoexam\AppData\Local\Temp\ipykernel_4868\2178482200.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row["temperature"] = __temperature_forecast(row)
C:\Users\demoexam\AppData\Local\Temp\ipykernel_4868\2178482200.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row["date_year"] = row["date_year"]-1

[2]

C:\Users\demoexam\AppData\Local\Temp\ipykernel_4868\2178482200.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row["temperature"] = __temperature_forecast(row)
C:\Users\demoexam\AppData\Local\Temp\ipykernel_4868\2178482200.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row["date_year"] = row["date_year"]-1

[2]

KeyboardInterrupt

In [71]:
params = {
    "latitude": 51.505713,
    "longitude": 104.139225,
    "start_date": "2008-09-12",
    "end_date": "2008-09-12",
    "hourly": ["temperature_2m"]
}

openmeteo = openmeteo_requests.Client()
responses = openmeteo.weather_api("https://archive-api.open-meteo.com/v1/archive", params=params)
response = responses[0]
current = response.Hourly()
temperatures = current.Variables(0).ValuesAsNumpy()

In [72]:
temperatures

array([14.7039995, 16.654001 , 19.204    , 20.804    , 21.004002 ,
       21.154001 , 21.054    , 20.354    , 19.604    , 18.854    ,
       17.954    , 17.504    , 16.854    , 16.354    , 15.304    ,
       14.4539995, 14.304    , 14.054    , 13.054    , 13.404    ,
       13.404    , 13.154    , 12.9539995, 12.754    ], dtype=float32)